/*!
 * comrade_jni::api — the Dart/Flutter FFI boundary, generated by
 * flutter_rust_bridge (FRB) v2.
 *
 * This is the *second* foreign ABI exported from this one cdylib. It is a
 * peer of, not a replacement for, the uniffi surface in [`crate`]: Kotlin's
 * background services (`WakeWordService`, `RelayConnectionService`,
 * `ModelDownloadService`, `CommandDispatcher`) must be able to reach Rust
 * without waking the Flutter engine, so they keep calling the uniffi
 * bindings, while the UI calls these functions from Dart.
 *
 * # One runtime, not two
 *
 * Every function here resolves [`crate::global_runtime`] — the same
 * `Arc<RwLock<ComradeRuntime>>` that `crate::Comrade` holds. That is load
 * bearing, not tidiness: `comrade_storage::EncryptedStore::open` opens the
 * vault with `redb::Database::create`, and redb takes an exclusive file lock,
 * so a second `ComradeRuntime` unlocking the same directory fails outright.
 * See `docs/FRONTEND_STRATEGY.md` §4 D2 and this crate's module header.
 *
 * # Sync vs async, and why it matters here
 *
 * FRB runs a plain `fn` on its own worker thread pool and an `async fn` on its
 * own Tokio runtime. `ComradeRuntime`'s cheap accessors use
 * `RwLock::blocking_read`/`blocking_write`, which **panic** if called from
 * inside a Tokio reactor — so those stay plain `fn` (a worker thread has no
 * ambient reactor, exactly like the JNA thread the uniffi tier is called on),
 * and only the methods that genuinely need a reactor are `async fn`. The
 * split below is deliberately identical to the one in [`crate::Comrade`].
 *
 * `#[frb(sync)]` — which runs the body *on the Dart isolate thread*, blocking
 * it — is used only for the handful of pure, allocation-cheap helpers that
 * touch no runtime state at all.
 *
 * # Regenerating the bindings
 *
 * `src/frb_generated.rs` and the Dart side are produced by:
 *
 * ```text
 * flutter_rust_bridge_codegen generate \
 *   --rust-input crate::api \
 *   --rust-root crates/comrade_jni \
 *   --dart-output <flutter-app>/lib/src/rust \
 *   --no-add-mod-to-lib --no-web
 * ```
 *
 * `--no-add-mod-to-lib` because `mod frb_generated;` is already declared by
 * hand in lib.rs, next to `uniffi::setup_scaffolding!`. The Dart package needs
 * `flutter_rust_bridge` + `freezed_annotation` as dependencies and
 * `build_runner` + `freezed` as dev-dependencies — the bridged enums
 * (`BridgeEvent`, `CallSignal`, `UiError`) generate freezed unions, and
 * codegen refuses to finish without them.
 *
 * The mirror declarations below exist because FRB only bridges types it can
 * see in the crate it parses; the DTOs live in `comrade_ui`/`comrade_core`.
 * They are a straight field-for-field restatement — **if you add a field to a
 * DTO, add it here too**, or codegen will fail with a field mismatch.
 */

use std::sync::Arc;

use comrade_ui::ComradeRuntime;
use flutter_rust_bridge::frb;
use tokio::sync::RwLock;

use crate::frb_generated::StreamSink;

// `pub use`, not `use`: the generated `frb_generated.rs` refers to every
// bridged type as `crate::api::<Name>`, so each one has to be nameable through
// this module. (Re-exporting them is harmless — this crate is a cdylib; it has
// no Rust downstream.)
pub use crate::{KeypairDto, WorkspaceKeyLabel};
pub use comrade_core::call::{CallMediaKind, CallSignal, HangupReason, IceStrategy};
pub use comrade_ui::{
    BridgeEvent, CallRecordDto, CallSessionDto, CallSignalDto, ChitthiDto, ComradeDto, ContactDto,
    ConversationDto, CrisisResourceDto, DirectMessageDto, FoundProfileDto, IceServerDto,
    IdentityDto, JournalEntryDto, MediaBytesDto, MediaMessageDto, MeshStatusDto, MessageDto,
    MessageRequestDto, MetricDto, PresenceDto, ProfileDto, TaraMessageDto, TurnServerStatusDto,
    UiError, UpiIntentDto, WorkspaceDto,
};

/// The process-global runtime every function in this module reads.
///
/// `pub(crate)` rather than private so `crate`'s tests can assert — with
/// `Arc::ptr_eq` — that this ABI and the uniffi one really are looking at one
/// object. Never exported to Dart (`ComradeRuntime` is not an FRB type).
pub(crate) fn runtime() -> &'static Arc<RwLock<ComradeRuntime>> {
    crate::global_runtime()
}

/// Runs once, when the Dart side first loads the library.
///
/// `setup_default_user_utils` routes the `log` crate to logcat/oslog and
/// installs a panic hook that logs the backtrace. The hook only *observes* —
/// it does not stop unwinding — so uniffi's `catch_unwind` at the Kotlin
/// boundary still turns a panic into a `PanicException` rather than a crash.
/// This crate itself logs through `tracing`, not `log`; the bridge is for
/// flutter_rust_bridge's own diagnostics.
#[frb(init)]
pub fn init_app() {
    flutter_rust_bridge::setup_default_user_utils();
}

// ── Mirrors of the DTOs that live in comrade_ui / comrade_core ───────────────
//
// FRB's parser only sees this crate, so each foreign type used in a signature
// needs a `#[frb(mirror(..))]` restatement. These generate the Dart classes;
// the real types are still the ones in comrade_ui/comrade_core.

#[frb(mirror(WorkspaceDto))]
pub struct _WorkspaceDto {
    pub key: String,
    pub label: String,
    pub active: bool,
    pub relay_connected: bool,
    pub mesh_active: bool,
    pub couple_sandbox: bool,
}

#[frb(mirror(IdentityDto))]
pub struct _IdentityDto {
    pub npub: String,
    pub has_secret: bool,
}

#[frb(mirror(UpiIntentDto))]
pub struct _UpiIntentDto {
    pub amount_inr: f64,
    pub vpa: String,
    pub uri: String,
}

#[frb(mirror(ChitthiDto))]
pub struct _ChitthiDto {
    pub id: String,
    pub author: String,
    pub content: String,
    pub created_at: u64,
    pub reply_to: Option<String>,
}

#[frb(mirror(DirectMessageDto))]
pub struct _DirectMessageDto {
    pub id: String,
    pub sender: String,
    pub content: String,
    pub created_at: u64,
    pub upi_intents: Vec<UpiIntentDto>,
    pub reply_to: Option<String>,
}

#[frb(mirror(MessageDto))]
pub struct _MessageDto {
    pub id: String,
    pub peer: String,
    pub content: String,
    pub created_at: u64,
    pub outgoing: bool,
    pub status: Option<String>,
    pub reply_to: Option<String>,
}

#[frb(mirror(ConversationDto))]
pub struct _ConversationDto {
    pub peer: String,
    pub alias: Option<String>,
    pub peer_name: Option<String>,
    pub last_message: String,
    pub last_at: u64,
    pub last_outgoing: bool,
    pub comrade: bool,
    pub online: bool,
}

#[frb(mirror(MessageRequestDto))]
pub struct _MessageRequestDto {
    pub peer: String,
    pub last_message: String,
    pub last_at: u64,
}

#[frb(mirror(ProfileDto))]
pub struct _ProfileDto {
    pub npub: String,
    pub username: Option<String>,
}

#[frb(mirror(FoundProfileDto))]
pub struct _FoundProfileDto {
    pub npub: String,
    pub name: Option<String>,
    pub about: Option<String>,
}

#[frb(mirror(ContactDto))]
pub struct _ContactDto {
    pub npub: String,
    pub alias: String,
    pub name: Option<String>,
    pub comrade: bool,
}

#[frb(mirror(ComradeDto))]
pub struct _ComradeDto {
    pub npub: String,
    pub alias: String,
    pub name: Option<String>,
    pub online: bool,
    pub last_seen_at: u64,
    pub peer_marked_us: bool,
}

#[frb(mirror(PresenceDto))]
pub struct _PresenceDto {
    pub peer: String,
    pub online: bool,
    pub last_seen_at: u64,
    pub peer_marked_us: bool,
}

#[frb(mirror(MetricDto))]
pub struct _MetricDto {
    pub key: String,
    pub value: u64,
}

#[frb(mirror(JournalEntryDto))]
pub struct _JournalEntryDto {
    pub id: String,
    pub text: String,
    pub mood: Option<String>,
    pub created_at: u64,
}

#[frb(mirror(TaraMessageDto))]
pub struct _TaraMessageDto {
    pub id: String,
    pub text: String,
    pub from_tara: bool,
    pub crisis: bool,
    pub created_at: u64,
}

#[frb(mirror(CrisisResourceDto))]
pub struct _CrisisResourceDto {
    pub name: String,
    pub contact: String,
    pub note: String,
}

#[frb(mirror(IceServerDto))]
pub struct _IceServerDto {
    pub urls: Vec<String>,
    pub username: Option<String>,
    pub credential: Option<String>,
}

#[frb(mirror(TurnServerStatusDto))]
pub struct _TurnServerStatusDto {
    pub configured: bool,
    pub url: Option<String>,
}

#[frb(mirror(CallSessionDto))]
pub struct _CallSessionDto {
    pub call_id: String,
    pub peer: String,
    pub media: String,
    pub ice_servers: Vec<IceServerDto>,
}

#[frb(mirror(CallSignalDto))]
pub struct _CallSignalDto {
    pub call_id: String,
    pub peer: String,
    pub media: String,
    pub signal: CallSignal,
    pub created_at: u64,
}

#[frb(mirror(CallRecordDto))]
pub struct _CallRecordDto {
    pub id: String,
    pub peer: String,
    pub media: String,
    pub incoming: bool,
    pub outcome: String,
    pub started_at: u64,
    pub duration_secs: u64,
}

#[frb(mirror(MediaMessageDto))]
pub struct _MediaMessageDto {
    pub event_id: String,
    pub url: String,
    pub mime_type: String,
    pub caption: String,
    pub sender: String,
    pub created_at: u64,
    pub size: u64,
    pub outgoing: bool,
}

#[frb(mirror(MediaBytesDto))]
pub struct _MediaBytesDto {
    pub mime_type: String,
    pub base64: String,
}

#[frb(mirror(MeshStatusDto))]
pub struct _MeshStatusDto {
    pub active: bool,
    pub peer_count: u64,
}

// `crate::KeypairDto` and `crate::WorkspaceKeyLabel` are declared in this same
// crate (they are uniffi `Record`s in lib.rs), so FRB's parser already sees
// them through `cargo expand` and bridges them directly — mirroring them here
// too would give the codegen two objects under one key.

#[frb(mirror(CallMediaKind))]
pub enum _CallMediaKind {
    Audio,
    Video,
}

#[frb(mirror(HangupReason))]
pub enum _HangupReason {
    Normal,
    Declined,
    Busy,
    Missed,
    Cancelled,
    Failed,
    Unknown,
}

#[frb(mirror(IceStrategy))]
pub enum _IceStrategy {
    StunOnly,
    StunAndTurn,
}

#[frb(mirror(CallSignal))]
pub enum _CallSignal {
    Offer {
        sdp: String,
    },
    Answer {
        sdp: String,
    },
    Ice {
        candidate: String,
        sdp_mid: Option<String>,
        sdp_m_line_index: Option<u16>,
    },
    Ringing,
    Busy,
    Hangup {
        reason: HangupReason,
    },
}

#[frb(mirror(BridgeEvent))]
pub enum _BridgeEvent {
    IncomingChitthi(ChitthiDto),
    IncomingDirectMessage(DirectMessageDto),
    IncomingMedia(MediaMessageDto),
    IncomingCallSignal(CallSignalDto),
    IncomingMessageRequest(MessageRequestDto),
    MessageStatus {
        peer: String,
        message_ids: Vec<String>,
        status: String,
    },
    PeerProfileUpdated {
        peer: String,
        name: Option<String>,
    },
    ComradePresence {
        peer: String,
        name: Option<String>,
        online: bool,
        at: u64,
    },
    MeshStatusChanged(MeshStatusDto),
    LedgerUpdated {
        ledger: String,
    },
}

#[frb(mirror(UiError))]
pub enum _UiError {
    UnknownWorkspace(String),
    Transition(String),
    NoIdentity,
    StoreLocked,
    Crypto(String),
    Storage(String),
    VaultLocked,
    Engine(String),
}

// ── Stateless helpers (no runtime needed) ────────────────────────────────────
//
// `#[frb(sync)]`: pure, microsecond-scale, and called from build methods, so
// paying a Dart `Future` round-trip for them would be silly. Nothing here
// touches the runtime lock, so blocking the isolate thread is free.

/// The comrade_jni crate version (e.g. "0.1.0").
#[frb(sync)]
pub fn version() -> String {
    crate::version()
}

/// A freshly generated secp256k1 keypair, Bech32-encoded. Standalone — doesn't
/// touch the encrypted store; see [`generate_identity`] and [`unlock_vault`]
/// for the store-backed identity flow every UI screen actually drives.
#[frb(sync)]
pub fn generate_keypair() -> Result<KeypairDto, UiError> {
    crate::generate_keypair()
}

/// Derive the npub from an nsec Bech32 string, or `None` if it doesn't parse.
#[frb(sync)]
pub fn npub_from_nsec(nsec: String) -> Option<String> {
    crate::npub_from_nsec(nsec)
}

/// The display label for a workspace discriminant, or `None` for an unknown key.
#[frb(sync)]
pub fn workspace_label(workspace: String) -> Option<String> {
    crate::workspace_label(workspace)
}

/// Every workspace discriminant and its label — a stable, store-free list
/// (contrast [`workspaces`], which also reports which one is active).
#[frb(sync)]
pub fn all_workspaces() -> Vec<WorkspaceKeyLabel> {
    crate::all_workspaces()
}

// ── Runtime lifecycle ────────────────────────────────────────────────────────

/// Materialise the process-global runtime, if some other caller (e.g. Kotlin
/// constructing `Comrade()`) has not already. The Dart counterpart of
/// `Comrade()`; there is no handle to hold onto because there is nothing to
/// hold — every function below finds the same runtime on its own.
pub fn init_runtime() {
    let _ = runtime();
}

/// [`init_runtime`], but seeding the runtime with an explicit relay set —
/// AUDIT.md COMMS-03's isolated-relay test hook. Only takes effect if this is
/// what first creates the runtime; the shipping app calls [`init_runtime`].
pub fn init_runtime_with_relays(relays: Vec<String>) {
    let _ = crate::global_runtime_with_relays(relays);
}

/// Open the encrypted store, restore or seed the identity, build the engines,
/// and start the background feed/DM loops. Safe to call more than once
/// (returns the already-loaded identity) — including when the *other* ABI
/// already unlocked it, which is the whole point of the shared runtime.
pub async fn unlock_vault(path: String, passphrase: String) -> Result<IdentityDto, UiError> {
    let mut guard = runtime().write().await;
    let identity = guard.unlock_vault(&path, &passphrase).await?;
    guard.spawn_event_loops();
    Ok(identity)
}

pub async fn is_vault_unlocked() -> bool {
    runtime().read().await.is_vault_unlocked()
}

pub async fn is_store_unlocked() -> bool {
    runtime().read().await.is_store_unlocked()
}

/// Re-lock the vault: abort the background feed/DM/sakha loops and drop the
/// store, engines, and in-memory identity.
pub async fn lock_vault() {
    runtime().write().await.lock_vault().await
}

// ── Identity ─────────────────────────────────────────────────────────────────

pub fn generate_identity() -> Result<IdentityDto, UiError> {
    runtime().blocking_write().generate_identity()
}

pub fn current_identity() -> Option<IdentityDto> {
    runtime().blocking_read().current_identity()
}

pub fn extract_payments(text: String) -> Result<Vec<UpiIntentDto>, UiError> {
    runtime().blocking_read().extract_payments(&text)
}

// ── Workspace controller ─────────────────────────────────────────────────────

pub fn workspaces() -> Vec<WorkspaceDto> {
    runtime().blocking_read().workspaces()
}

pub fn current_workspace() -> WorkspaceDto {
    runtime().blocking_read().current_workspace()
}

/// Async because switching also starts/stops the Saathi mesh engine to match.
pub async fn toggle_workspace(target: String) -> Result<WorkspaceDto, UiError> {
    runtime().write().await.toggle_workspace(&target).await
}

/// Async for the same reason as [`toggle_workspace`].
pub async fn back() -> WorkspaceDto {
    runtime().write().await.back().await
}

/// Snapshot of the off-grid Saathi mesh's live status, for seeding a
/// connectivity indicator before the first `BridgeEvent::MeshStatusChanged`
/// arrives. Never fails: the mesh being off is a valid, common state.
pub fn mesh_status() -> MeshStatusDto {
    runtime().blocking_read().mesh_status()
}

// ── Sabha (public feed) ──────────────────────────────────────────────────────

pub fn fetch_sabha_timeline() -> Result<Vec<ChitthiDto>, UiError> {
    runtime().blocking_read().fetch_sabha_timeline()
}

/// Takes a cheap, synchronous handle snapshot under the guard and runs the
/// relay round-trip after it is dropped — AUDIT P2: never hold the runtime
/// lock across a network await, or one slow relay stalls every other call.
pub async fn broadcast_chitthi(
    content: String,
    reply_to: Option<String>,
) -> Result<String, UiError> {
    let handles = runtime().read().await.handles();
    handles.broadcast_chitthi(&content, reply_to).await
}

/// Broadcast a Chitthi under a throwaway or scoped persona instead of this
/// device's identity — the anonymous-thoughts path.
///
/// `scope` of `None` signs the post with a key used exactly once, so two
/// anonymous Chitthis cannot be linked to each other. `Some(label)` derives a
/// stable persona for that label, so replies can reach the same pseudonym while
/// it stays unlinkable to the identity. See `docs/BITCHAT_ADOPTION.md` for what
/// this does and does not hide.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn broadcast_anonymous_chitthi(
    content: String,
    scope: Option<String>,
) -> Result<String, UiError> {
    let handles = runtime().read().await.handles();
    handles
        .broadcast_anonymous_chitthi(&content, scope.as_deref())
        .await
}

// ── Vault (E2E DMs) ──────────────────────────────────────────────────────────

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn send_dm(target: String, content: String) -> Result<MessageDto, UiError> {
    let handles = runtime().read().await.handles();
    handles.send_dm(&target, &content).await
}

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn send_dm_reply(
    target: String,
    content: String,
    reply_to: Option<String>,
) -> Result<MessageDto, UiError> {
    let handles = runtime().read().await.handles();
    handles
        .send_dm_reply(&target, &content, reply_to.as_deref())
        .await
}

/// Retry every DM sitting in the sender outbox because no relay would take it.
/// Returns how many a relay accepted this pass.
///
/// A background loop already flushes on a cadence (and once at launch); call
/// this when the platform reports connectivity came back, so a queued message
/// goes out immediately instead of on the next tick.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn flush_outbox() -> Result<u64, UiError> {
    let handles = runtime().read().await.handles();
    handles.flush_outbox().await.map(|n| n as u64)
}

/// How many DMs are waiting for a relay that will take them — for a "queued"
/// indicator in the chat list.
pub fn outbox_pending() -> u64 {
    runtime().blocking_read().outbox_pending() as u64
}

/// **Panic wipe.** Destroy every locally stored value — identity keys, DM
/// history, journal, Tara thread, queued mail — then re-lock, leaving the
/// runtime as it was before its first unlock.
///
/// Irreversible, and deliberately not a duress feature: it wipes rather than
/// hides, and it needs the app open and unlocked. After it returns, send the
/// user back to onboarding.
pub async fn panic_wipe() -> Result<(), UiError> {
    runtime().write().await.panic_wipe().await
}

/// Device-local delivery counters — bare tallies with no identities, ids,
/// content, or timestamps, for a diagnostics screen. Nothing here is ever
/// uploaded; [`panic_wipe`] clears them.
pub fn metrics_snapshot() -> Vec<MetricDto> {
    runtime().blocking_read().metrics_snapshot()
}

pub fn conversations() -> Result<Vec<ConversationDto>, UiError> {
    runtime().blocking_read().conversations()
}

pub fn messages_with(peer: String) -> Result<Vec<MessageDto>, UiError> {
    runtime().blocking_read().messages_with(&peer)
}

/// Full encrypted-media history with `peer`, oldest first — the media
/// counterpart of [`messages_with`].
pub fn media_with(peer: String) -> Result<Vec<MediaMessageDto>, UiError> {
    runtime().blocking_read().media_with(&peer)
}

// ── Message requests (stranger gating) + receipts ────────────────────────────

pub fn message_requests() -> Result<Vec<MessageRequestDto>, UiError> {
    runtime().blocking_read().message_requests()
}

/// Async because accepting fires a background profile-share + receipt send
/// that needs a live reactor to `tokio::spawn` onto.
pub async fn accept_request(peer: String) -> Result<(), UiError> {
    runtime().read().await.accept_request(&peer)
}

pub fn block_conversation(peer: String) -> Result<(), UiError> {
    runtime().blocking_read().block_conversation(&peer)
}

/// Async for the same reason as [`accept_request`].
pub async fn mark_conversation_read(peer: String) -> Result<(), UiError> {
    runtime().read().await.mark_conversation_read(&peer)
}

// ── Profile & contacts ───────────────────────────────────────────────────────

pub fn profile() -> Result<ProfileDto, UiError> {
    runtime().blocking_read().profile()
}

pub async fn set_username(name: String) -> Result<ProfileDto, UiError> {
    runtime().write().await.set_username(&name).await
}

pub fn add_contact(npub: String, alias: String) -> Result<ContactDto, UiError> {
    runtime().blocking_read().add_contact(&npub, &alias)
}

pub fn set_contact_alias(npub: String, alias: String) -> Result<ContactDto, UiError> {
    runtime().blocking_read().set_contact_alias(&npub, &alias)
}

pub fn remove_contact(npub: String) -> Result<bool, UiError> {
    runtime().blocking_read().remove_contact(&npub)
}

pub fn list_contacts() -> Result<Vec<ContactDto>, UiError> {
    runtime().blocking_read().list_contacts()
}

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn search_profiles(query: String) -> Result<Vec<FoundProfileDto>, UiError> {
    let handles = runtime().read().await.handles();
    handles.search_profiles(&query).await
}

/// Detaches the refresher and drops the shared lock before the relay
/// round-trip (AUDIT P2).
pub async fn refresh_peer_profiles() -> Result<u64, UiError> {
    let refresher = runtime().read().await.profile_refresher()?;
    let changed = refresher.run().await?;
    Ok(changed as u64)
}

// ── Comrades (chosen-peer presence) ──────────────────────────────────────────

/// Choose (or un-choose) a contact as a comrade.
///
/// What this discloses, stated plainly: from now on this device tells *that one
/// peer* — nobody else, and no relay — when it is online, and it starts
/// believing what they say about their own presence. It does **not** subscribe
/// us to theirs; we see them only once they have marked us back, which is what
/// [`ComradeDto`]'s `peer_marked_us` is for.
///
/// Async for the same reason as [`accept_request`]: the beacon telling that
/// peer about the change is a background `tokio::spawn`, which needs a live
/// reactor.
pub async fn set_comrade(npub: String, comrade: bool) -> Result<ContactDto, UiError> {
    runtime().read().await.set_comrade(&npub, comrade)
}

/// Every comrade with their live presence, online first.
pub fn comrades() -> Result<Vec<ComradeDto>, UiError> {
    runtime().blocking_read().comrades()
}

/// One peer's live presence, or `None` if no beacon ever arrived from them
/// (they haven't chosen us back, or haven't been online since).
pub fn peer_presence(npub: String) -> Result<Option<PresenceDto>, UiError> {
    runtime().blocking_read().peer_presence(&npub)
}

/// Announce this device's presence to every comrade, returning how many beacons
/// a relay accepted. Frontends call this on foreground/background transitions;
/// the native heartbeat covers the rest. Never fails — presence is a courtesy,
/// so a locked vault is a quiet `0`, not an error.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn announce_presence(online: bool) -> u64 {
    let handles = runtime().read().await.handles();
    handles.announce_presence(online).await
}

// ── Journal (strictly local) ─────────────────────────────────────────────────

pub fn add_journal_entry(text: String, mood: Option<String>) -> Result<JournalEntryDto, UiError> {
    runtime()
        .blocking_read()
        .add_journal_entry(&text, mood.as_deref())
}

pub fn journal_entries() -> Result<Vec<JournalEntryDto>, UiError> {
    runtime().blocking_read().journal_entries()
}

pub fn delete_journal_entry(id: String) -> Result<bool, UiError> {
    runtime().blocking_read().delete_journal_entry(&id)
}

// ── Tara (reflective companion — strictly local, not therapy) ────────────────

/// Persist the user's message, compute Tara's on-device reply, persist and
/// return it. `crisis == true` on the reply means the UI must surface
/// [`tara_crisis_resources`] with it.
pub fn tara_send(text: String) -> Result<TaraMessageDto, UiError> {
    runtime().blocking_read().tara_send(&text)
}

/// The whole Tara thread, oldest-first (chat order).
pub fn tara_thread() -> Result<Vec<TaraMessageDto>, UiError> {
    runtime().blocking_read().tara_thread()
}

/// Delete the entire Tara thread; returns how many turns were removed.
pub fn clear_tara_thread() -> Result<u64, UiError> {
    runtime().blocking_read().clear_tara_thread()
}

/// The opener shown while the thread is empty — shaped by recent journal mood
/// markers only, never entry text.
pub fn tara_opener() -> Result<String, UiError> {
    runtime().blocking_read().tara_opener()
}

/// The crisis helplines Tara hands off to.
pub fn tara_crisis_resources() -> Vec<CrisisResourceDto> {
    runtime().blocking_read().tara_crisis_resources()
}

// ── Calls (voice/video signaling) ────────────────────────────────────────────

pub fn call_ice_servers() -> Vec<IceServerDto> {
    runtime().blocking_read().call_ice_servers()
}

pub fn call_ice_servers_for(strategy: IceStrategy) -> Vec<IceServerDto> {
    runtime()
        .blocking_read()
        .call_ice_servers_for(strategy.as_str())
}

/// The 4-emoji short authentication string (SAS) for the in-progress call
/// whose local/remote SDPs are `local_sdp`/`remote_sdp`. `None` when either
/// side's SDP carries no `a=fingerprint:` line to derive a code from.
pub fn call_sas(local_sdp: String, remote_sdp: String) -> Option<Vec<String>> {
    runtime().blocking_read().call_sas(&local_sdp, &remote_sdp)
}

pub fn set_turn_server(url: String, username: String, credential: String) -> Result<(), UiError> {
    runtime()
        .blocking_read()
        .set_turn_server(&url, &username, &credential)
}

/// The "is a relay configured" diagnostic status. Carries the URL only; never
/// the username/credential.
pub fn turn_server_status() -> TurnServerStatusDto {
    runtime().blocking_read().turn_server_status()
}

pub fn place_call(peer: String, media: CallMediaKind) -> Result<CallSessionDto, UiError> {
    runtime().blocking_read().place_call(&peer, media.as_str())
}

/// `signal` crosses as the real [`CallSignal`] enum, not a JSON blob — only
/// this crate still round-trips it through JSON internally, since that's the
/// wire format the encrypted DM channel carries.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn send_call_signal(
    peer: String,
    call_id: String,
    media: CallMediaKind,
    signal: CallSignal,
) -> Result<(), UiError> {
    let signal_json = serde_json::to_string(&signal).map_err(|e| UiError::Engine(e.to_string()))?;
    let handles = runtime().read().await.handles();
    handles
        .send_call_signal(&peer, &call_id, media.as_str(), &signal_json)
        .await
}

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn hangup_call(
    peer: String,
    call_id: String,
    media: CallMediaKind,
    reason: HangupReason,
) -> Result<(), UiError> {
    let handles = runtime().read().await.handles();
    handles
        .hangup_call(&peer, &call_id, media.as_str(), reason.as_str())
        .await
}

#[allow(clippy::too_many_arguments)]
pub fn log_call(
    peer: String,
    call_id: String,
    media: CallMediaKind,
    incoming: bool,
    outcome: String,
    started_at: u64,
    duration_secs: u64,
) -> Result<CallRecordDto, UiError> {
    runtime().blocking_read().log_call(
        &peer,
        &call_id,
        media.as_str(),
        incoming,
        &outcome,
        started_at,
        duration_secs,
    )
}

pub fn call_history(peer: Option<String>) -> Result<Vec<CallRecordDto>, UiError> {
    runtime().blocking_read().call_history(peer.as_deref())
}

// ── Encrypted media (NIP-94/96 · Blossom) ────────────────────────────────────

/// `bytes` crosses as a native byte array.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn upload_and_send_media(
    target_pubkey: String,
    bytes: Vec<u8>,
    mime_type: String,
    caption: String,
) -> Result<MediaMessageDto, UiError> {
    let handles = runtime().read().await.handles();
    handles
        .upload_and_send_media(&target_pubkey, bytes, &mime_type, &caption)
        .await
}

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn download_and_decrypt_media(event_id: String) -> Result<MediaBytesDto, UiError> {
    let handles = runtime().read().await.handles();
    handles.download_and_decrypt_media(&event_id).await
}

// ── Sakha/Sakhi CRDT ledger ──────────────────────────────────────────────────

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn sync_ledger() -> Result<String, UiError> {
    let handles = runtime().read().await.handles();
    handles.sync_ledger().await
}

// ── Push events ──────────────────────────────────────────────────────────────

/// Every [`BridgeEvent`], as a Dart `Stream`.
///
/// The Dart counterpart of `Comrade::set_event_listener`, and deliberately
/// sourced from the *same* two `tokio::sync::broadcast` channels the uniffi
/// listener forwards — `broadcast` fans out to every receiver, so a Kotlin
/// service listening through uniffi and a Flutter UI listening through this
/// stream both see every event, simultaneously, with neither starving the
/// other.
///
/// Two channels are merged, exactly as `set_event_listener` forwards two:
/// the critical stream (DMs, requests, call signals, mesh/ledger updates) and
/// the separate, small, deliberately-lossy `IncomingChitthi` feed stream (see
/// `comrade_ui::ComradeRuntime::subscribe_feed_events`, AUDIT.md COMMS-04), so
/// a public-feed flood can never delay a call signal queued behind it.
///
/// Subscribing late is safe but not retroactive: `broadcast` receivers only
/// see events sent after they subscribe, so call this before [`unlock_vault`].
/// Dropping the Dart subscription ends the task.
pub async fn bridge_event_stream(sink: StreamSink<BridgeEvent>) {
    let (critical_rx, feed_rx) = {
        let guard = runtime().read().await;
        (guard.subscribe_events(), guard.subscribe_feed_events())
    };
    // `sink.add` returns `Err` once Dart has dropped the subscription.
    pump_bridge_events(critical_rx, feed_rx, |event| sink.add(event).is_ok()).await
}

/// The fan-in half of [`bridge_event_stream`], with the Dart sink replaced by
/// `emit` (returning `false` when the consumer is gone).
///
/// Split out purely so it can be tested: a real `StreamSink` needs a live Dart
/// isolate port to construct, which no Rust test can provide. `pub(crate)`, so
/// FRB's parser leaves it alone — only `pub` items in this module become Dart
/// functions.
pub(crate) async fn pump_bridge_events<F>(
    mut critical_rx: tokio::sync::broadcast::Receiver<BridgeEvent>,
    mut feed_rx: tokio::sync::broadcast::Receiver<BridgeEvent>,
    mut emit: F,
) where
    F: FnMut(BridgeEvent) -> bool,
{
    // `broadcast::Receiver::recv` is cancel-safe, so `select!` dropping the
    // loser's future each iteration cannot lose an event on that channel.
    //
    // `Lagged` means this receiver fell behind *that channel's own* ring
    // buffer — never a cross-channel effect, since the two have independent
    // buffers. Log the skip count and keep going rather than tear the stream
    // down; `Closed` only happens when the runtime itself is going away.
    loop {
        let event = tokio::select! {
            r = critical_rx.recv() => r,
            r = feed_rx.recv() => r,
        };
        match event {
            Ok(event) => {
                if !emit(event) {
                    break;
                }
            }
            Err(tokio::sync::broadcast::error::RecvError::Lagged(skipped)) => {
                tracing::warn!(
                    skipped,
                    "Dart event stream fell behind a broadcast channel's capacity; \
                     some events were skipped"
                );
            }
            Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
        }
    }
}
