/*!
 * comrade_jni — the Android FFI boundary, generated by uniffi-rs.
 *
 * This crate used to hand-write one `#[no_mangle] pub extern "C" fn
 * Java_mullu_comrade_ComradeCore_<name>` per operation, marshal every argument
 * and return value through `serde_json`, and catch panics with a bespoke
 * `guard_json` helper (see git history). All of that is now generated:
 * `uniffi::setup_scaffolding!` below emits the `extern "C"` layer, and
 * [`Comrade`]'s exported methods are lowered/lifted directly — no JSON, no
 * manual panic guard (uniffi's scaffolding catches panics itself and turns
 * them into a `PanicException` on the Kotlin side).
 *
 * # Two foreign ABIs, one runtime
 *
 * This cdylib exports **two** independent FFI surfaces:
 *
 *  1. the uniffi scaffolding below (`uniffi_comrade_*` / `ffi_comrade_*`
 *     symbols), which Kotlin — the app *and* the background services
 *     (`WakeWordService`, `RelayConnectionService`, `ModelDownloadService`,
 *     `CommandDispatcher`) — drives through the generated JNA bindings, and
 *  2. the flutter_rust_bridge scaffolding in [`api`] (`frb_*` symbols), which
 *     a Dart/Flutter UI drives.
 *
 * They must live in **one** shared library, because two cdylibs would each get
 * their own copy of this crate's `static`s, hence two [`ComradeRuntime`]s, and
 * `comrade_storage::EncryptedStore::open` opens the vault with
 * `redb::Database::create` — redb takes an exclusive file lock, so the second
 * unlock of the same vault directory fails outright. Hence
 * [`global_runtime`]: the single, process-lifetime `ComradeRuntime` that both
 * ABIs read and write. See `docs/FRONTEND_STRATEGY.md` §4 D2.
 *
 * Shape:
 *  • Free functions ([`version`], [`generate_keypair`], …) — stateless crypto
 *    and workspace-metadata helpers that don't need a live runtime.
 *  • [`Comrade`] — an opaque uniffi `Object` (handed to Kotlin as a single
 *    `Comrade()` instance, constructed once and reused) that is now a thin
 *    handle onto [`global_runtime`] rather than the owner of its own
 *    `ComradeRuntime` — the same "one shared instance for the process" shape
 *    as the desktop's `Arc<RwLock<ComradeRuntime>>` managed state, wrapping every
 *    [`comrade_ui::ComradeRuntime`] method the Vault (DMs/calls/media),
 *    Sabha (public feed) and Identity (profile/contacts/workspace) engines
 *    expose. Methods that only read/write `ComradeRuntime`'s own fields stay
 *    synchronous (`.blocking_read()`/`.blocking_write()`); methods whose call
 *    path needs a live Tokio reactor (a relay round-trip, or a fire-and-forget
 *    `tokio::spawn` receipt/profile-share deep inside `comrade_ui`) are
 *    `async fn` under `#[uniffi::export(async_runtime = "tokio")]`, which
 *    Kotlin sees as a `suspend fun` and which `async-compat` drives on a
 *    runtime of its own — no process-global `tokio::runtime::Runtime` to
 *    manage by hand any more.
 *  • [`BridgeEventListener`] — a uniffi callback interface Kotlin implements
 *    to receive [`BridgeEvent`]s pushed live, replacing the old `pollEvent()`
 *    JNI call that Kotlin had to re-invoke on a 600ms timer.
 *
 * # Invariant: listener callbacks run off the Tokio runtime
 *
 * [`BridgeEventListener::on_event`] is always invoked from a dedicated,
 * plain `std::thread` (see [`spawn_event_forwarder`]) — never from a Tokio
 * worker. This is deliberate: if Kotlin's implementation re-enters any of
 * this crate's *synchronous* methods (the ones using `.blocking_read()`/
 * `.blocking_write()`, e.g. [`Comrade::workspaces`]) from inside `on_event`,
 * that call is safe precisely because the callback is not running on a
 * thread with an ambient Tokio reactor — `blocking_read`/`blocking_write`
 * panic when called from *inside* one. Keep this true for any future change
 * to the forwarding path: never invoke `on_event` from a `tokio::spawn`ed
 * task or any other Tokio-driven context.
 */

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, OnceLock};

use comrade_core::call::{CallMediaKind, CallSignal, HangupReason, IceStrategy};
use comrade_core::crypto::KeyProfile;
use comrade_core::handoff::{AttachmentRoute, HandoffSignal};
use comrade_core::share::transport::RelayPolicy;
use comrade_core::share::ShareSignal;
use comrade_core::together::{MusicLink, Recording, ServiceAccess, TogetherContent};
use comrade_state::AppWorkspace;
use comrade_ui::{
    AppAction, AttentionDayDto, AttentionSummaryDto, BridgeEvent, CallRecordDto, CallSessionDto,
    ChatCommand, ChitthiDto, CommandSpec, ComradeDto, ComradeRuntime, ContactDto, ConversationDto,
    CrisisResourceDto, FocusSessionDto, FoundProfileDto, IceServerDto, IdentityDto,
    JournalEntryDto, MediaBytesDto, MediaMessageDto, Mention, MentionMatchDto, MeshStatusDto,
    MessageDto, MessageRequestDto, MetricDto, MusicService, OfferOutcomeDto, PeerProfileDto,
    PlayPlan, PlayRoute, PlayTargetDto, PresenceDto, ProfileDto, ReactionDto, ReadingDto,
    ShareVerdictDto, TaraChatDto, TaraMessageDto, TaskDto, TaskState, TogetherSessionDto,
    TurnServerStatusDto, UiError, UpiIntentDto, WorkspaceDto,
};
use tokio::sync::RwLock;
use tracing::warn;

uniffi::setup_scaffolding!("comrade");

pub mod api;
mod frb_generated;

// ── The process-global runtime ────────────────────────────────────────────────

/// The one [`ComradeRuntime`] for the whole process, shared by *both* foreign
/// ABIs this cdylib exports (see the module header). Not `pub` — nothing
/// outside this crate should be able to build a second one.
static RUNTIME: OnceLock<Arc<RwLock<ComradeRuntime>>> = OnceLock::new();

/// The process-global [`ComradeRuntime`], created on first use.
///
/// Both [`Comrade`] (uniffi → Kotlin) and every function in [`api`]
/// (flutter_rust_bridge → Dart) resolve to *this* handle, so an unlock done
/// through one ABI is immediately visible through the other and the vault's
/// redb file is only ever opened once.
pub(crate) fn global_runtime() -> &'static Arc<RwLock<ComradeRuntime>> {
    RUNTIME.get_or_init(|| Arc::new(RwLock::new(ComradeRuntime::new())))
}

/// [`global_runtime`], but seeding it with an explicit relay set if — and only
/// if — it has not been created yet (AUDIT.md COMMS-03's isolated-relay test
/// hook, reached from [`Comrade::new_with_relays`]).
///
/// First caller wins: there is exactly one runtime per process, so a later
/// call cannot retarget engines that may already be connected. That is logged
/// rather than silently ignored, and never fails — the caller still gets a
/// working handle.
pub(crate) fn global_runtime_with_relays(
    relays: Vec<String>,
) -> &'static Arc<RwLock<ComradeRuntime>> {
    let mut seeded = false;
    let runtime = RUNTIME.get_or_init(|| {
        seeded = true;
        Arc::new(RwLock::new(ComradeRuntime::with_relays(relays)))
    });
    if !seeded {
        warn!(
            "new_with_relays: the process-global runtime already exists; \
             keeping its current relay set"
        );
    }
    runtime
}

// ── Stateless helpers (no ComradeRuntime instance needed) ────────────────────

/// The comrade_jni crate version (e.g. "0.1.0").
#[uniffi::export]
pub fn version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

/// A freshly generated secp256k1 keypair, Bech32-encoded. Standalone —
/// doesn't touch the encrypted store; see [`Comrade::generate_identity`] and
/// [`Comrade::unlock_vault`] for the store-backed identity flow every UI
/// screen actually drives.
#[derive(uniffi::Record)]
pub struct KeypairDto {
    pub npub: String,
    pub nsec: String,
}

#[uniffi::export]
pub fn generate_keypair() -> Result<KeypairDto, UiError> {
    let profile = KeyProfile::generate().map_err(|e| UiError::Crypto(e.to_string()))?;
    Ok(KeypairDto {
        npub: profile.npub,
        nsec: profile.nsec,
    })
}

/// Derive the npub from an nsec Bech32 string, or `None` if it doesn't parse.
#[uniffi::export]
pub fn npub_from_nsec(nsec: String) -> Option<String> {
    KeyProfile::from_nsec(&nsec).ok().map(|p| p.npub)
}

/// The display label for a workspace discriminant (`"Base"`,
/// `"OffGridTravel"`, `"CoupleSandboxSakha"`, `"CoupleSandboxSakhi"`), or
/// `None` for an unknown key.
#[uniffi::export]
pub fn workspace_label(workspace: String) -> Option<String> {
    AppWorkspace::from_key(&workspace).map(|ws| ws.label().to_string())
}

/// A workspace discriminant paired with its display label.
#[derive(uniffi::Record)]
pub struct WorkspaceKeyLabel {
    pub key: String,
    pub label: String,
}

/// Every workspace discriminant and its label — a stable, store-free list
/// (contrast [`Comrade::workspaces`], which also reports which one is active).
/// Which road an attachment of this size takes — hosted, or straight to the
/// other device.
///
/// Exported rather than reimplemented per frontend because the two roads have
/// different failure modes a person has to be told about, and a UI that guessed
/// the threshold would eventually guess it differently from the core that
/// enforces it. See `comrade_core::handoff::route_for_bytes`.
#[uniffi::export]
pub fn attachment_route_for_bytes(total_bytes: u64) -> AttachmentRoute {
    comrade_core::handoff::route_for_bytes(total_bytes)
}

/// A fresh id scoping every signal of one attachment handoff.
///
/// Exported rather than minted per frontend because the id *is* the replay
/// guard: 128 bits from the same CSPRNG everywhere, so no frontend can weaken it
/// to a counter or a timestamp that a third party could predict and use to
/// inject an `Accept` for a transfer nobody offered. See
/// `comrade_core::handoff::new_transfer_id`.
#[uniffi::export]
pub fn new_attachment_transfer_id() -> String {
    comrade_core::handoff::new_transfer_id()
}

#[uniffi::export]
pub fn all_workspaces() -> Vec<WorkspaceKeyLabel> {
    AppWorkspace::all()
        .iter()
        .map(|ws| WorkspaceKeyLabel {
            key: ws.key().to_string(),
            label: ws.label().to_string(),
        })
        .collect()
}

// ── Push events ───────────────────────────────────────────────────────────────

/// Implemented in Kotlin to receive [`BridgeEvent`]s as they happen. Register
/// with [`Comrade::set_event_listener`] — ideally right after constructing
/// [`Comrade`] and before [`Comrade::unlock_vault`], so no event emitted by
/// the background feed/DM loops arrives before anyone is listening.
#[uniffi::export(foreign)]
pub trait BridgeEventListener: Send + Sync {
    fn on_event(&self, event: BridgeEvent);
}

/// Bounded, drop-oldest queue of [`BridgeEvent`]s bridging the async
/// forwarder task (producer, on a Tokio worker) and the dedicated listener
/// thread (consumer, see [`spawn_event_forwarder`]). `std::sync::mpsc` has no
/// way to evict from the middle of its buffer, so a slow/absent consumer
/// would either grow it unboundedly (`channel()`) or block the producer
/// (`sync_channel()`) — neither is acceptable here — hence this small
/// hand-rolled `Mutex<VecDeque<_>>` + `Condvar` instead of a new dependency.
struct EventQueue {
    state: std::sync::Mutex<EventQueueState>,
    ready: std::sync::Condvar,
}

struct EventQueueState {
    items: std::collections::VecDeque<BridgeEvent>,
    closed: bool,
}

impl EventQueue {
    /// Comfortably above a burst of ordinary traffic; a listener that's
    /// fallen behind by this much has bigger problems than a dropped event.
    const CAPACITY: usize = 1024;

    fn new() -> Self {
        Self {
            state: std::sync::Mutex::new(EventQueueState {
                items: std::collections::VecDeque::new(),
                closed: false,
            }),
            ready: std::sync::Condvar::new(),
        }
    }

    /// Push `event`, dropping (and logging) the oldest queued event first if
    /// already at capacity — the queue must never grow unboundedly, and the
    /// producer (a Tokio worker forwarding the broadcast channel) must never
    /// block waiting for the consumer thread to catch up.
    fn push(&self, event: BridgeEvent) {
        let mut state = self.state.lock().unwrap_or_else(|e| e.into_inner());
        if state.items.len() >= Self::CAPACITY {
            state.items.pop_front();
            warn!(
                capacity = Self::CAPACITY,
                "event listener queue at capacity; dropped the oldest queued event"
            );
        }
        state.items.push_back(event);
        drop(state);
        self.ready.notify_one();
    }

    /// Block the calling (dedicated) thread until an event is ready, or
    /// return `None` once [`Self::close`] has been called and the queue has
    /// drained.
    fn pop_blocking(&self) -> Option<BridgeEvent> {
        let mut state = self.state.lock().unwrap_or_else(|e| e.into_inner());
        loop {
            if let Some(event) = state.items.pop_front() {
                return Some(event);
            }
            if state.closed {
                return None;
            }
            state = self.ready.wait(state).unwrap_or_else(|e| e.into_inner());
        }
    }

    fn close(&self) {
        self.state.lock().unwrap_or_else(|e| e.into_inner()).closed = true;
        self.ready.notify_all();
    }
}

/// Forward one `BridgeEvent` channel to `listener` until it closes.
///
/// Two parts: a Tokio task drains the broadcast channel and pushes onto a
/// bounded, drop-oldest [`EventQueue`]; a dedicated, named `std::thread`
/// drains that queue and calls `listener.on_event` — deliberately off the
/// Tokio runtime (see the module-header invariant) so a Kotlin listener that
/// synchronously re-enters a `blocking_read`/`blocking_write` method from
/// inside `on_event` can never panic.
///
/// A `Lagged` error means this receiver fell behind *that broadcast
/// channel's own* capacity and some events on it were skipped — never a
/// cross-channel effect, since each of the two channels `set_event_listener`
/// forwards has its own independent ring buffer — logged with the skip count
/// rather than silently continuing.
fn spawn_event_forwarder(
    mut rx: tokio::sync::broadcast::Receiver<BridgeEvent>,
    listener: Arc<dyn BridgeEventListener>,
) {
    let queue = Arc::new(EventQueue::new());

    let consumer_queue = queue.clone();
    std::thread::Builder::new()
        .name("comrade-event-listener".to_string())
        .spawn(move || {
            while let Some(event) = consumer_queue.pop_blocking() {
                listener.on_event(event);
            }
        })
        .expect("failed to spawn the dedicated event-listener thread");

    let producer_queue = queue;
    tokio::spawn(async move {
        loop {
            match rx.recv().await {
                Ok(event) => producer_queue.push(event),
                Err(tokio::sync::broadcast::error::RecvError::Lagged(skipped)) => {
                    warn!(skipped, "event listener fell behind the broadcast channel's own capacity; some events were skipped");
                }
                Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
            }
        }
        producer_queue.close();
    });
}

// ── Comrade — the live runtime handle ────────────────────────────────────────

/// The Kotlin-facing handle to the native core. Kotlin constructs this
/// exactly once and calls every method on that one instance — uniffi hands it
/// to Kotlin as `Arc<Comrade>` under the hood, so cloning the reference is
/// cheap and every method call is thread-safe.
///
/// The handle no longer *owns* a [`ComradeRuntime`]: every instance borrows
/// the process-global one (see [`global_runtime`]) so the Dart ABI in [`api`]
/// drives the same engines, the same unlocked store, and the same event bus.
/// Constructing two `Comrade`s is therefore harmless — they are two references
/// to one runtime, not two runtimes.
#[derive(uniffi::Object)]
pub struct Comrade {
    inner: Arc<RwLock<ComradeRuntime>>,
    /// Per-handle, deliberately *not* process-global: each `Comrade` may
    /// register (at most) one listener, exactly as before this became a shared
    /// runtime. Two handles registering two listeners means two forwarders
    /// over the same broadcast channels, which is correct — `broadcast`
    /// fans out to every receiver.
    listener_registered: AtomicBool,
}

impl Comrade {
    /// Build a handle over an explicit runtime. Not exported over FFI: the
    /// only foreign-reachable constructors are [`Comrade::new`] and
    /// [`Comrade::new_with_relays`], both of which bind the process-global
    /// runtime. Tests use this to get an isolated runtime (and therefore an
    /// isolated redb vault) per test.
    fn with_runtime(inner: Arc<RwLock<ComradeRuntime>>) -> Arc<Self> {
        Arc::new(Self {
            inner,
            listener_registered: AtomicBool::new(false),
        })
    }
}

#[uniffi::export(async_runtime = "tokio")]
impl Comrade {
    #[uniffi::constructor]
    pub fn new() -> Arc<Self> {
        Self::with_runtime(global_runtime().clone())
    }

    /// Like [`Comrade::new`], but connecting new engines to `relays` instead
    /// of the public default set. AUDIT.md COMMS-03's isolated-relay test
    /// hook: a two-installation/two-instance device test points both sides
    /// at one local relay instead of the public internet. Not used by the
    /// shipping app (which always calls [`Comrade::new`]).
    ///
    /// Only takes effect if it is what first creates the process-global
    /// runtime — see [`global_runtime_with_relays`].
    #[uniffi::constructor]
    pub fn new_with_relays(relays: Vec<String>) -> Arc<Self> {
        Self::with_runtime(global_runtime_with_relays(relays).clone())
    }

    // ── Push events ───────────────────────────────────────────────────────

    /// Register `listener` to receive every future [`BridgeEvent`]. Only the
    /// first call takes effect (idempotent, like [`Comrade::unlock_vault`]) —
    /// the app registers one listener for its lifetime.
    ///
    /// Forwards *two* independent channels to the same `listener` — the
    /// critical stream (DMs, requests, call signals, terminal call events,
    /// mesh/ledger updates) and the separate, small, deliberately-lossy
    /// `IncomingChitthi` stream (see `comrade_ui::ComradeRuntime::subscribe_feed_events`,
    /// AUDIT.md COMMS-04) — so a public-feed flood dropping old, unconsumed
    /// Chitthis on its own channel can never delay or starve a call
    /// signal/DM/request queued behind it on the critical one.
    pub async fn set_event_listener(&self, listener: Arc<dyn BridgeEventListener>) {
        if self.listener_registered.swap(true, Ordering::SeqCst) {
            return;
        }
        let guard = self.inner.read().await;
        let critical_rx = guard.subscribe_events();
        let feed_rx = guard.subscribe_feed_events();
        drop(guard);
        spawn_event_forwarder(critical_rx, listener.clone());
        spawn_event_forwarder(feed_rx, listener);
    }

    // ── Vault unlock / lifecycle ────────────────────────────────────────────

    /// Open the encrypted store, restore or seed the identity, build the
    /// engines, and start the background feed/DM loops. Safe to call more
    /// than once (returns the already-loaded identity).
    pub async fn unlock_vault(
        &self,
        path: String,
        passphrase: String,
    ) -> Result<IdentityDto, UiError> {
        let mut guard = self.inner.write().await;
        let identity = guard.unlock_vault(&path, &passphrase).await?;
        guard.spawn_event_loops();
        Ok(identity)
    }

    pub fn is_vault_unlocked(&self) -> bool {
        self.inner.blocking_read().is_vault_unlocked()
    }

    pub fn is_store_unlocked(&self) -> bool {
        self.inner.blocking_read().is_store_unlocked()
    }

    /// Re-lock the vault: abort the background feed/DM/sakha loops and drop
    /// the store, engines, and in-memory identity — see
    /// `comrade_ui::ComradeRuntime::lock_vault`. Async because stopping a
    /// live Saathi mesh engine (if the workspace has one running) awaits its
    /// shutdown; every other step is synchronous state teardown.
    pub async fn lock_vault(&self) {
        self.inner.write().await.lock_vault().await
    }

    // ── Identity ────────────────────────────────────────────────────────────

    pub fn generate_identity(&self) -> Result<IdentityDto, UiError> {
        self.inner.blocking_write().generate_identity()
    }

    pub fn current_identity(&self) -> Option<IdentityDto> {
        self.inner.blocking_read().current_identity()
    }

    pub fn extract_payments(&self, text: String) -> Result<Vec<UpiIntentDto>, UiError> {
        self.inner.blocking_read().extract_payments(&text)
    }

    // ── Workspace controller ────────────────────────────────────────────────

    pub fn workspaces(&self) -> Vec<WorkspaceDto> {
        self.inner.blocking_read().workspaces()
    }

    pub fn current_workspace(&self) -> WorkspaceDto {
        self.inner.blocking_read().current_workspace()
    }

    /// Async (not because a reactor is strictly needed for the workspace
    /// switch itself, but because it now also starts/stops the Saathi mesh
    /// engine to match — see `comrade_ui::ComradeRuntime::toggle_workspace`).
    pub async fn toggle_workspace(&self, target: String) -> Result<WorkspaceDto, UiError> {
        self.inner.write().await.toggle_workspace(&target).await
    }

    /// Async for the same reason as [`Comrade::toggle_workspace`].
    pub async fn back(&self) -> WorkspaceDto {
        self.inner.write().await.back().await
    }

    /// Snapshot of the off-grid Saathi mesh's live status (mDNS discovery +
    /// Gossipsub) — for seeding a UI's connectivity indicator before the
    /// first [`BridgeEvent::MeshStatusChanged`] arrives. Never fails: the
    /// mesh being off is a valid, common state, not an error.
    pub fn mesh_status(&self) -> MeshStatusDto {
        self.inner.blocking_read().mesh_status()
    }

    // ── Bluetooth transport ─────────────────────────────────────────────────
    //
    // The platform owns the radio (GATT roles, advertising, scanning, MTU
    // negotiation); the core owns everything that decides what goes on the
    // wire. These four calls are the whole seam between them, and they are
    // deliberately shaped so the radio never waits on the core: each takes the
    // runtime's *read* guard only long enough to clone an `Arc`, then works on
    // that. A scan callback blocking behind a relay round trip would stall the
    // BLE stack itself.

    /// Tell the core whether a platform BLE service is scanning and
    /// advertising. Until this is true, Bluetooth is not offered as a route.
    pub fn ble_set_active(&self, active: bool) {
        self.inner.blocking_read().ble_router().set_active(active);
    }

    /// Report the negotiated MTU as **usable application payload bytes** per
    /// write — the platform subtracts its own ATT overhead first. Fragment
    /// sizing follows this.
    pub fn ble_set_mtu(&self, mtu: u32) {
        self.inner
            .blocking_read()
            .ble_router()
            .set_mtu(mtu as usize);
    }

    /// Hand in one packet heard from a BLE peer.
    ///
    /// The core dedups it, decides whether to relay it onward (the relayed copy
    /// appears in the next [`Comrade::ble_drain_outbound`]), and reassembles.
    /// A completed envelope goes through the same ingress a WiFi-mesh frame
    /// does. Infallible on purpose: a malformed packet from a stranger in radio
    /// range is an ordinary event, not an error the radio should handle.
    pub fn ble_deliver(&self, packet: Vec<u8>) {
        let router = self.inner.blocking_read().ble_router();
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or_default();
        router.deliver(&packet, now);
    }

    /// Collect packets the core wants transmitted, oldest first, draining the
    /// queue. Called by the radio on its own cadence.
    pub fn ble_drain_outbound(&self) -> Vec<Vec<u8>> {
        self.inner.blocking_read().ble_router().drain_outbound()
    }

    // ── Sabha (public feed) ─────────────────────────────────────────────────

    pub fn fetch_sabha_timeline(&self) -> Result<Vec<ChitthiDto>, UiError> {
        self.inner.blocking_read().fetch_sabha_timeline()
    }

    /// Takes a cheap, synchronous handle snapshot under the guard (see
    /// `comrade_ui::ComradeRuntime::handles`) and runs the relay round-trip
    /// after it is dropped — AUDIT P2: never hold the runtime lock across a
    /// network await, or one slow/unreachable relay stalls every other
    /// bridge call behind it.
    pub async fn broadcast_chitthi(
        &self,
        content: String,
        reply_to: Option<String>,
    ) -> Result<String, UiError> {
        let handles = self.inner.read().await.handles();
        handles.broadcast_chitthi(&content, reply_to).await
    }

    /// Broadcast a Chitthi under a throwaway or scoped persona instead of this
    /// device's identity — the anonymous-thoughts path.
    ///
    /// `scope` of `None` signs the post with a key used exactly once, so two
    /// anonymous Chitthis cannot be linked to each other. `Some(label)` derives
    /// a stable persona for that label, so replies can reach the same pseudonym
    /// while it stays unlinkable to the identity. See
    /// `comrade_ui::ComradeRuntime::broadcast_anonymous_chitthi`, and
    /// `docs/BITCHAT_ADOPTION.md` for what this does and does not hide.
    ///
    /// See [`Comrade::broadcast_chitthi`]'s doc comment for the lock discipline.
    pub async fn broadcast_anonymous_chitthi(
        &self,
        content: String,
        scope: Option<String>,
    ) -> Result<String, UiError> {
        let handles = self.inner.read().await.handles();
        handles
            .broadcast_anonymous_chitthi(&content, scope.as_deref())
            .await
    }

    // ── Vault (E2E DMs) ──────────────────────────────────────────────────────

    /// See [`Comrade::broadcast_chitthi`]'s doc comment for the lock discipline.
    pub async fn send_dm(&self, target: String, content: String) -> Result<MessageDto, UiError> {
        let handles = self.inner.read().await.handles();
        handles.send_dm(&target, &content).await
    }

    /// See [`Comrade::broadcast_chitthi`]'s doc comment for the lock discipline.
    pub async fn send_dm_reply(
        &self,
        target: String,
        content: String,
        reply_to: Option<String>,
    ) -> Result<MessageDto, UiError> {
        let handles = self.inner.read().await.handles();
        handles
            .send_dm_reply(&target, &content, reply_to.as_deref())
            .await
    }

    /// React to a message in `peer`'s thread with `emoji` — or take an existing
    /// reaction back by passing the same emoji again. Returns the reaction now
    /// standing, or `None` if the tap withdrew one.
    ///
    /// The toggle is decided on the Rust side (see
    /// `ComradeRuntime::toggle_reaction`) so the two frontends cannot disagree
    /// about what tapping an already-sent emoji means.
    ///
    /// See [`Comrade::broadcast_chitthi`]'s doc comment for the lock discipline.
    pub async fn toggle_reaction(
        &self,
        peer: String,
        target_id: String,
        emoji: String,
    ) -> Result<Option<ReactionDto>, UiError> {
        let handles = self.inner.read().await.handles();
        handles.toggle_reaction(&peer, &target_id, &emoji).await
    }

    /// Every reaction in `peer`'s conversation, oldest first, from the encrypted
    /// store — so a thread opens with its reactions already drawn.
    pub fn reactions(&self, peer: String) -> Result<Vec<ReactionDto>, UiError> {
        self.inner.blocking_read().reactions(&peer)
    }

    /// Retry every DM sitting in the sender outbox because no relay would take
    /// it. Returns how many a relay accepted this pass.
    ///
    /// A background loop already flushes on a cadence (and once at launch);
    /// call this when the platform reports connectivity came back, so a queued
    /// message goes out immediately instead of on the next tick.
    ///
    /// See [`Comrade::broadcast_chitthi`]'s doc comment for the lock discipline.
    pub async fn flush_outbox(&self) -> Result<u64, UiError> {
        let handles = self.inner.read().await.handles();
        handles.flush_outbox().await.map(|n| n as u64)
    }

    /// How many DMs are waiting for a relay that will take them — for a
    /// "queued" indicator in the chat list.
    pub fn outbox_pending(&self) -> u64 {
        self.inner.blocking_read().outbox_pending() as u64
    }

    /// **Panic wipe.** Destroy every locally stored value — identity keys, DM
    /// history, journal, Tara thread, queued mail — then re-lock, leaving the
    /// runtime as it was before its first unlock.
    ///
    /// Irreversible, and deliberately not a duress feature: it wipes rather
    /// than hides, and it needs the app open and unlocked. After it returns,
    /// send the user back to onboarding.
    pub async fn panic_wipe(&self) -> Result<(), UiError> {
        self.inner.write().await.panic_wipe().await
    }

    /// Device-local delivery counters — bare tallies with no identities, ids,
    /// content, or timestamps, for a diagnostics screen. Nothing here is ever
    /// uploaded; the panic wipe clears them.
    pub fn metrics_snapshot(&self) -> Vec<MetricDto> {
        self.inner.blocking_read().metrics_snapshot()
    }

    pub fn conversations(&self) -> Result<Vec<ConversationDto>, UiError> {
        self.inner.blocking_read().conversations()
    }

    pub fn messages_with(&self, peer: String) -> Result<Vec<MessageDto>, UiError> {
        self.inner.blocking_read().messages_with(&peer)
    }

    /// Full encrypted-media history with `peer`, oldest first — the media
    /// counterpart of [`Comrade::messages_with`], for rendering past
    /// attachments inline after a restart, not just ones received live.
    pub fn media_with(&self, peer: String) -> Result<Vec<MediaMessageDto>, UiError> {
        self.inner.blocking_read().media_with(&peer)
    }

    // ── Message requests (stranger gating) + receipts ──────────────────────

    pub fn message_requests(&self) -> Result<Vec<MessageRequestDto>, UiError> {
        self.inner.blocking_read().message_requests()
    }

    /// Async (not because the underlying call is itself `async fn`, but
    /// because accepting a request fires a background profile-share + receipt
    /// send that needs a live reactor to `tokio::spawn` onto — see
    /// `comrade_ui::ComradeRuntime::accept_request`).
    pub async fn accept_request(&self, peer: String) -> Result<(), UiError> {
        self.inner.read().await.accept_request(&peer)
    }

    pub fn block_conversation(&self, peer: String) -> Result<(), UiError> {
        self.inner.blocking_read().block_conversation(&peer)
    }

    /// Async for the same reason as [`Comrade::accept_request`] — the
    /// read-receipt send is a background `tokio::spawn`.
    ///
    /// Returns the read position the thread had *before* this call (unix
    /// seconds, 0 = never opened), which is what lets the UI open at the first
    /// unread message instead of the newest one.
    pub async fn mark_conversation_read(&self, peer: String) -> Result<u64, UiError> {
        self.inner.read().await.mark_conversation_read(&peer)
    }

    // ── Profile & contacts ──────────────────────────────────────────────────

    pub fn profile(&self) -> Result<ProfileDto, UiError> {
        self.inner.blocking_read().profile()
    }

    pub async fn set_username(&self, name: String) -> Result<ProfileDto, UiError> {
        self.inner.write().await.set_username(&name).await
    }

    /// Set (or clear, with an empty string) this identity's bio, and republish.
    pub async fn set_about(&self, about: String) -> Result<ProfileDto, UiError> {
        self.inner.write().await.set_about(&about).await
    }

    /// Everything a profile page draws for one peer, from the local cache alone.
    pub fn peer_profile(&self, npub: String) -> Result<PeerProfileDto, UiError> {
        self.inner.blocking_read().peer_profile(&npub)
    }

    /// A peer's cached avatar bytes, or `None` to draw initials. Never touches
    /// the network.
    pub fn peer_avatar(&self, npub: String) -> Result<Option<MediaBytesDto>, UiError> {
        self.inner.blocking_read().peer_avatar(&npub)
    }

    /// Whether peer-published pictures may be fetched at all (default on).
    pub fn remote_avatars_enabled(&self) -> Result<bool, UiError> {
        self.inner.blocking_read().remote_avatars_enabled()
    }

    pub fn set_remote_avatars_enabled(&self, on: bool) -> Result<(), UiError> {
        self.inner.blocking_read().set_remote_avatars_enabled(on)
    }

    pub fn add_contact(&self, npub: String, alias: String) -> Result<ContactDto, UiError> {
        self.inner.blocking_read().add_contact(&npub, &alias)
    }

    pub fn set_contact_alias(&self, npub: String, alias: String) -> Result<ContactDto, UiError> {
        self.inner.blocking_read().set_contact_alias(&npub, &alias)
    }

    pub fn remove_contact(&self, npub: String) -> Result<bool, UiError> {
        self.inner.blocking_read().remove_contact(&npub)
    }

    pub fn list_contacts(&self) -> Result<Vec<ContactDto>, UiError> {
        self.inner.blocking_read().list_contacts()
    }

    /// See [`Comrade::broadcast_chitthi`]'s doc comment for the lock discipline.
    pub async fn search_profiles(&self, query: String) -> Result<Vec<FoundProfileDto>, UiError> {
        let handles = self.inner.read().await.handles();
        handles.search_profiles(&query).await
    }

    /// Detaches the refresher and drops the shared lock before the relay
    /// round-trip (AUDIT P2: never hold the runtime lock across a network
    /// await), matching `comrade_ui::ComradeRuntime::refresh_peer_profiles`.
    pub async fn refresh_peer_profiles(&self) -> Result<u64, UiError> {
        let refresher = self.inner.read().await.profile_refresher()?;
        let changed = refresher.run().await?;
        Ok(changed as u64)
    }

    // ── Comrades (chosen-peer presence) ─────────────────────────────────────

    /// Choose (or un-choose) a contact as a comrade — see
    /// `comrade_ui::ComradeRuntime::set_comrade` for what that discloses.
    ///
    /// Async for the same reason as [`Comrade::accept_request`]: the beacon
    /// telling that peer about the change is a background `tokio::spawn`,
    /// which needs a live reactor.
    pub async fn set_comrade(&self, npub: String, comrade: bool) -> Result<ContactDto, UiError> {
        self.inner.read().await.set_comrade(&npub, comrade)
    }

    /// Every comrade with their live presence, online first.
    pub fn comrades(&self) -> Result<Vec<ComradeDto>, UiError> {
        self.inner.blocking_read().comrades()
    }

    /// One peer's live presence, or `None` if no beacon ever arrived from
    /// them (they haven't chosen us back, or haven't been online since).
    pub fn peer_presence(&self, npub: String) -> Result<Option<PresenceDto>, UiError> {
        self.inner.blocking_read().peer_presence(&npub)
    }

    /// Announce this device's presence to every comrade, returning how many
    /// beacons a relay accepted. Called by the Android shell on foreground /
    /// background transitions; the native heartbeat covers the rest.
    ///
    /// See [`Comrade::broadcast_chitthi`]'s doc comment for the lock discipline.
    pub async fn announce_presence(&self, online: bool) -> u64 {
        let handles = self.inner.read().await.handles();
        handles.announce_presence(online).await
    }

    // ── The nudge (abandoned drafts) ─────────────────────────────────────────

    /// There is unsent text in `peer`'s composer, as of now — see
    /// `comrade_ui::ComradeRuntime::note_draft`.
    ///
    /// Synchronous, unlike its presence neighbours, precisely because a
    /// frontend calls it on a keystroke: it takes the runtime lock for a
    /// hash-map insert and touches no store, no relay and no reactor, so a
    /// suspend function (and the `runBlocking` every caller would wrap it in)
    /// would cost more than the work.
    ///
    /// `try_read`, not `blocking_read`: this runs on the UI thread, and a
    /// courtesy signal must never make a text field wait behind a slow
    /// `lock_vault`/`unlock_vault` (both of which hold the write lock across
    /// awaits). A skipped report costs at most one nudge, and the next
    /// keystroke reports again.
    pub fn note_draft(&self, peer: String) {
        if let Ok(rt) = self.inner.try_read() {
            rt.note_draft(&peer);
        }
    }

    /// That draft is gone — cleared, or left behind when the thread closed.
    /// Call it whenever a conversation closes; an empty composer does nothing.
    ///
    /// Skipped under contention like [`Comrade::note_draft`], which fails in
    /// the harmless direction: the only thing holding the write lock long
    /// enough to matter is a vault lock or unlock, and locking clears the
    /// watch anyway.
    pub fn abandon_draft(&self, peer: String) {
        if let Ok(rt) = self.inner.try_read() {
            rt.abandon_draft(&peer);
        }
    }

    /// Tell every comrade, once, that this person might need them — the
    /// deliberate trigger behind the breathing screen. Returns how many nudges
    /// a relay accepted.
    ///
    /// Async, unlike its two neighbours, because this one does reach a relay:
    /// it is a deliberate tap, not a keystroke, so it can afford to be
    /// awaited. Never throws — a locked vault or no comrades is a quiet `0`.
    ///
    /// See [`Comrade::broadcast_chitthi`]'s doc comment for the lock discipline.
    pub async fn nudge_comrades(&self) -> u64 {
        let handles = self.inner.read().await.handles();
        handles.nudge_comrades().await
    }

    // ── Journal (strictly local) ─────────────────────────────────────────────

    pub fn add_journal_entry(
        &self,
        text: String,
        mood: Option<String>,
    ) -> Result<JournalEntryDto, UiError> {
        self.inner
            .blocking_read()
            .add_journal_entry(&text, mood.as_deref())
    }

    pub fn journal_entries(&self) -> Result<Vec<JournalEntryDto>, UiError> {
        self.inner.blocking_read().journal_entries()
    }

    pub fn delete_journal_entry(&self, id: String) -> Result<bool, UiError> {
        self.inner.blocking_read().delete_journal_entry(&id)
    }

    // ── Tara (reflective companion — strictly local, not therapy) ───────────

    /// Persist the user's message, compute Tara's on-device reply, persist and
    /// return it. `crisis == true` on the reply means the UI must surface
    /// [`Comrade::tara_crisis_resources`] with it.
    pub fn tara_send(&self, text: String) -> Result<TaraMessageDto, UiError> {
        self.inner.blocking_read().tara_send(&text)
    }

    /// The whole Tara thread, oldest-first (chat order).
    pub fn tara_thread(&self) -> Result<Vec<TaraMessageDto>, UiError> {
        self.inner.blocking_read().tara_thread()
    }

    /// Delete the entire Tara thread; returns how many turns were removed.
    pub fn clear_tara_thread(&self) -> Result<u64, UiError> {
        self.inner.blocking_read().clear_tara_thread()
    }

    /// The opener shown while the thread is empty — shaped by recent journal
    /// mood markers only, never entry text.
    pub fn tara_opener(&self) -> Result<String, UiError> {
        self.inner.blocking_read().tara_opener()
    }

    /// The crisis helplines Tara hands off to.
    pub fn tara_crisis_resources(&self) -> Vec<CrisisResourceDto> {
        self.inner.blocking_read().tara_crisis_resources()
    }

    // ── In-chat commands, tasks and offers ───────────────────────────────────

    /// What the text in a composer means. Pure and needs no vault, so Kotlin can
    /// call it on every keystroke — which is what the command bar does.
    pub fn parse_chat_command(&self, text: String) -> ChatCommand {
        self.inner.blocking_read().parse_chat_command(&text)
    }

    /// Every command the composer offers, for `/`-autocomplete and `/help`.
    pub fn chat_command_catalog(&self) -> Vec<CommandSpec> {
        self.inner.blocking_read().chat_command_catalog()
    }

    /// Every `@handle` in `text`, unresolved — for drawing chips while typing.
    pub fn chat_mentions(&self, text: String) -> Vec<Mention> {
        self.inner.blocking_read().chat_mentions(&text)
    }

    /// Every `@handle` in `text`, resolved against the saved contacts. A match
    /// with no `npub` and a non-empty `candidates` is an ambiguity the UI must
    /// ask about rather than resolve.
    pub fn resolve_mentions(&self, text: String) -> Result<Vec<MentionMatchDto>, UiError> {
        self.inner.blocking_read().resolve_mentions(&text)
    }

    /// How far a `/play` query gets without a network or a library.
    pub fn play_query(&self, query: String, service: Option<MusicService>) -> PlayTargetDto {
        self.inner.blocking_read().play_query(&query, service)
    }

    /// What to do about a `/play`, once the caller has searched its own library.
    ///
    /// `found_local_copy` is only consulted for [`PlayPlan::FindLocally`]; see
    /// [`comrade_ui::play_route`] for why a local file does not make a service
    /// link a local session.
    ///
    /// `link` and `access` are what decide a service track: the same Spotify URL
    /// is a session on a device with a Premium account signed in and a signpost
    /// on one without, and nothing in the URL distinguishes them. A frontend
    /// with no service integration passes
    /// [`comrade_core::together::ServiceAccess::none`] and gets exactly today's
    /// behaviour. Pure, so it takes no lock.
    pub fn play_route(
        &self,
        plan: PlayPlan,
        found_local_copy: bool,
        link: Option<MusicLink>,
        access: ServiceAccess,
    ) -> PlayRoute {
        comrade_ui::play_route(plan, found_local_copy, link, access)
    }

    /// Name a piece of work. `peer` of `None` is a note to self, which never
    /// touches a relay.
    pub async fn assign_task(
        &self,
        peer: Option<String>,
        text: String,
    ) -> Result<TaskDto, UiError> {
        let handles = self.inner.read().await.handles();
        handles.assign_task(peer, &text).await
    }

    /// Every task this device knows about, newest first.
    pub fn tasks(&self) -> Result<Vec<TaskDto>, UiError> {
        self.inner.blocking_read().tasks()
    }

    /// Move a task to `state` and tell the other party. Errors if this device
    /// has no standing to make that change.
    pub async fn set_task_state(&self, id: String, state: TaskState) -> Result<TaskDto, UiError> {
        let handles = self.inner.read().await.handles();
        handles.set_task_state(&id, state).await
    }

    /// Offer an in-app action to comrades. The outcome names who was told and
    /// why the others were not — a bare count could not tell "the cooldown is
    /// running" from "that person is not your comrade".
    pub async fn offer_action(
        &self,
        action: AppAction,
        peers: Vec<String>,
    ) -> Result<OfferOutcomeDto, UiError> {
        let handles = self.inner.read().await.handles();
        handles.offer_action(action, peers).await
    }

    /// Say something to Tara from inside a conversation — a private aside that
    /// never reaches the peer. See `ComradeRuntime::tara_aside`.
    pub fn tara_aside(&self, text: String) -> Result<TaraMessageDto, UiError> {
        self.inner.blocking_read().tara_aside(&text)
    }

    /// Ask Tara **in** the conversation — `@tara …`, which the peer sees. The
    /// counterpart to [`Self::tara_aside`]; see `RuntimeHandles::tara_in_chat`
    /// for the three ways this differs from a cloud assistant, and for why a
    /// question that trips the distress detector sends nothing.
    pub async fn tara_in_chat(&self, peer: String, text: String) -> Result<TaraChatDto, UiError> {
        let handles = self.inner.read().await.handles();
        handles.tara_in_chat(&peer, &text).await
    }

    // ── Attention (usage mirror · focus sessions · long read) ────────────────
    //
    // Strictly local, like the journal and Tara: nothing here is ever
    // networked. `date`/`today` are `YYYY-MM-DD` in the *device's* timezone —
    // Kotlin owns the calendar, because only it knows what that is.

    pub fn record_attention_day(
        &self,
        date: String,
        screen_minutes: u32,
        pickups: u32,
        doom_minutes: u32,
    ) -> Result<AttentionDayDto, UiError> {
        self.inner.blocking_read().record_attention_day(
            &date,
            screen_minutes,
            pickups,
            doom_minutes,
        )
    }

    pub fn attention_days(&self) -> Result<Vec<AttentionDayDto>, UiError> {
        self.inner.blocking_read().attention_days()
    }

    /// Today's rollup against the user's own recent medians.
    pub fn attention_summary(&self, today: String) -> Result<AttentionSummaryDto, UiError> {
        self.inner.blocking_read().attention_summary(&today)
    }

    /// The package names the user tagged as their own scroll traps. Comrade
    /// ships no built-in blacklist — see `ComradeRuntime::doom_apps`.
    pub fn doom_apps(&self) -> Result<Vec<String>, UiError> {
        self.inner.blocking_read().doom_apps()
    }

    pub fn set_doom_apps(&self, packages: Vec<String>) -> Result<Vec<String>, UiError> {
        self.inner.blocking_read().set_doom_apps(packages)
    }

    pub fn start_focus_session(
        &self,
        intent: String,
        planned_minutes: u32,
    ) -> Result<FocusSessionDto, UiError> {
        self.inner
            .blocking_read()
            .start_focus_session(&intent, planned_minutes)
    }

    /// Finish the running session; `None` if none was running. A session past
    /// its grace window is recorded as lapsed whatever `completed` says.
    pub fn finish_focus_session(
        &self,
        completed: bool,
    ) -> Result<Option<FocusSessionDto>, UiError> {
        self.inner.blocking_read().finish_focus_session(completed)
    }

    pub fn active_focus_session(&self) -> Result<Option<FocusSessionDto>, UiError> {
        self.inner.blocking_read().active_focus_session()
    }

    pub fn focus_sessions(&self) -> Result<Vec<FocusSessionDto>, UiError> {
        self.inner.blocking_read().focus_sessions()
    }

    pub fn suggested_focus_minutes(&self) -> Result<u32, UiError> {
        self.inner.blocking_read().suggested_focus_minutes()
    }

    /// The session lengths to offer. Infallible and vault-free — see
    /// `ComradeRuntime::focus_presets`.
    pub fn focus_presets(&self) -> Vec<u32> {
        self.inner.blocking_read().focus_presets()
    }

    pub fn focus_prompt(&self) -> Result<String, UiError> {
        self.inner.blocking_read().focus_prompt()
    }

    pub fn focus_reflection(&self, outcome: String) -> Result<String, UiError> {
        self.inner.blocking_read().focus_reflection(&outcome)
    }

    pub fn save_reading(&self, title: String, text: String) -> Result<ReadingDto, UiError> {
        self.inner.blocking_read().save_reading(&title, &text)
    }

    pub fn reading(&self) -> Result<Option<ReadingDto>, UiError> {
        self.inner.blocking_read().reading()
    }

    pub fn set_reading_position(&self, position: u32) -> Result<Option<ReadingDto>, UiError> {
        self.inner.blocking_read().set_reading_position(position)
    }

    pub fn clear_reading(&self) -> Result<bool, UiError> {
        self.inner.blocking_read().clear_reading()
    }

    // ── Calls (voice/video signaling) ───────────────────────────────────────

    pub fn call_ice_servers(&self) -> Vec<IceServerDto> {
        self.inner.blocking_read().call_ice_servers()
    }

    pub fn call_ice_servers_for(&self, strategy: IceStrategy) -> Vec<IceServerDto> {
        self.inner
            .blocking_read()
            .call_ice_servers_for(strategy.as_str())
    }

    /// The 4-emoji short authentication string (SAS) for the in-progress call
    /// whose local/remote SDPs are `local_sdp`/`remote_sdp` — see
    /// `comrade_ui::ComradeRuntime::call_sas`. `None` when either side's SDP
    /// carries no `a=fingerprint:` line to derive a code from.
    pub fn call_sas(&self, local_sdp: String, remote_sdp: String) -> Option<Vec<String>> {
        self.inner.blocking_read().call_sas(&local_sdp, &remote_sdp)
    }

    pub fn set_turn_server(
        &self,
        url: String,
        username: String,
        credential: String,
    ) -> Result<(), UiError> {
        self.inner
            .blocking_read()
            .set_turn_server(&url, &username, &credential)
    }

    /// The "is a relay configured" diagnostic status — see
    /// `comrade_ui::ComradeRuntime::turn_server_status`. Carries the URL only;
    /// never the username/credential.
    pub fn turn_server_status(&self) -> TurnServerStatusDto {
        self.inner.blocking_read().turn_server_status()
    }

    pub fn place_call(
        &self,
        peer: String,
        media: CallMediaKind,
    ) -> Result<CallSessionDto, UiError> {
        self.inner.blocking_read().place_call(&peer, media.as_str())
    }

    /// Recognise a Spotify / Apple Music / YouTube link and reduce it to what
    /// it identifies. Pure and offline — no audio is fetched and no account is
    /// touched; turning the id into a title needs the service's public
    /// catalogue API, which is the frontend's call to make.
    pub fn parse_music_link(&self, input: String) -> Option<MusicLink> {
        comrade_core::together::parse_music_link(&input)
    }

    /// How well a candidate in the listener's own library matches what the peer
    /// named — 1.0 on an ISRC agreement, 0.0 on an ISRC disagreement, a weighted
    /// title/artist/duration score otherwise. Above
    /// [`Comrade::together_match_confident`] a frontend may open it unasked.
    pub fn together_match_score(
        &self,
        want: Recording,
        have: Recording,
        want_ms: u64,
        have_ms: u64,
    ) -> f64 {
        comrade_core::together::match_score(&want, &have, want_ms, have_ms)
    }

    /// The bar above which a library match may be opened without asking.
    pub fn together_match_confident(&self) -> f64 {
        comrade_core::together::MATCH_CONFIDENT
    }

    /// Invite `peer` to watch or listen to something together.
    ///
    /// See [`Comrade::broadcast_chitthi`]'s doc comment for the lock discipline.
    pub async fn together_start(
        &self,
        peer: String,
        content: TogetherContent,
    ) -> Result<TogetherSessionDto, UiError> {
        let handles = self.inner.read().await.handles();
        handles.together_start(&peer, content).await
    }

    /// Accept the invitation we were sent.
    pub async fn together_join(&self) -> Result<(), UiError> {
        let handles = self.inner.read().await.handles();
        handles.together_join().await
    }

    /// Play, pause or seek — one call, because all three are one statement.
    ///
    /// `effective_in_ms` is a promise by the caller that it will apply the same
    /// change on its own player at that instant. A native player can defer a few
    /// tens of milliseconds imperceptibly, and then both sides change state on
    /// the *same* tick instead of one chasing the other. Pass 0 if you cannot.
    pub async fn together_set_state(
        &self,
        pos_ms: u64,
        playing: bool,
        effective_in_ms: u64,
    ) -> Result<(), UiError> {
        let handles = self.inner.read().await.handles();
        handles
            .together_set_state(pos_ms, playing, effective_in_ms)
            .await
    }

    /// Leave the session.
    pub async fn together_end(&self) -> Result<(), UiError> {
        let handles = self.inner.read().await.handles();
        handles.together_end().await
    }

    /// Report where our own player is, without sending anything.
    ///
    /// Synchronous and skipped under contention, exactly like
    /// [`Comrade::note_draft`]: a player calls this several times a second from
    /// its UI thread, and a position report is not worth waiting on a vault
    /// unlock for. Missing one only means the next drift verdict compares
    /// against a slightly older number.
    pub fn together_report_position(&self, pos_ms: u64, playing: bool, output_latency_ms: u64) {
        if let Ok(rt) = self.inner.try_read() {
            rt.together_report_position(pos_ms, playing, output_latency_ms);
        }
    }

    /// The live session, if there is one.
    pub fn together_session(&self) -> Option<TogetherSessionDto> {
        self.inner.blocking_read().together_session()
    }

    /// Declare whether a direct peer channel is carrying this session's signals,
    /// so they take it instead of a relay — tens of milliseconds against
    /// hundreds, which is what decides how tight the sync can be.
    ///
    /// `try_read` for the same reason as [`Self::together_report_position`], and
    /// a sharper one: this is called from WebRTC connection callbacks, and
    /// blocking one of those is the shape of two bugs this repo has already
    /// fixed. A skipped declaration costs one relay-routed signal.
    pub fn together_direct_ready(&self, ready: bool) {
        if let Ok(rt) = self.inner.try_read() {
            rt.together_direct_ready(ready);
        }
    }

    /// Hand over an envelope that arrived on the direct channel.
    ///
    /// Deliberately less privileged than the relay path — it cannot open a
    /// session, and the sender is the session's peer by definition rather than
    /// by anything in the payload. Unvalidated input either way: it is parsed
    /// and dropped on anything unexpected.
    pub fn together_receive_direct(&self, json: String) {
        if let Ok(rt) = self.inner.try_read() {
            rt.together_receive_direct(&json);
        }
    }

    /// Send one step of handing the file over — for the case `together`
    /// otherwise assumes away, where only one of you has what you are playing.
    pub async fn together_share(&self, signal: ShareSignal) -> Result<(), UiError> {
        let handles = self.inner.read().await.handles();
        handles.together_share(signal).await
    }

    /// Send one step of handing a **large attachment** over — the road a file
    /// takes when it is past [`comrade_core::media::MAX_MEDIA_BYTES`] and the
    /// hosted path cannot carry it.
    ///
    /// Deliberately not [`Self::together_share`]: that one refuses outside a live
    /// watch-together session, which is right for a playhead and wrong here —
    /// nobody starts a listening session to send a video file. The gate a handoff
    /// gets instead is on receipt, and it is the same one a call signal clears.
    /// See `comrade_core::handoff`.
    pub async fn attachment_handoff_send(
        &self,
        peer: String,
        transfer_id: String,
        signal: HandoffSignal,
    ) -> Result<(), UiError> {
        let handles = self.inner.read().await.handles();
        handles
            .attachment_handoff_send(&peer, &transfer_id, signal)
            .await
    }

    /// What this device does when the only path a transfer could take is
    /// somebody else's relay.
    pub fn share_relay_policy(&self) -> RelayPolicy {
        self.inner.blocking_read().share_relay_policy()
    }

    /// Change it, and remember it. Takes effect on the next transfer
    /// connection. Errors if the vault is locked — the choice still holds for
    /// this process, but it could not be written down.
    pub fn set_share_relay_policy(&self, policy: RelayPolicy) -> Result<(), UiError> {
        self.inner.blocking_read().set_share_relay_policy(policy)
    }

    /// Whether a transfer connection may be given TURN servers at all. Under
    /// the default policy it may not, so a relayed path is never gathered and
    /// the rule holds structurally rather than by later inspection.
    pub fn share_ice_servers_allowed(&self) -> bool {
        self.inner.blocking_read().share_ice_servers_allowed()
    }

    /// Judge the path ICE actually chose. `local_candidate_type` and
    /// `remote_candidate_type` come from the selected candidate pair in an
    /// `RTCStatsReport`; anything unrecognised is refused, never assumed direct.
    ///
    /// Synchronous and vault-free on purpose — a frontend calls this from
    /// inside a WebRTC callback, which is exactly the place a lock held across
    /// an await froze calls on "Connecting…" once already.
    pub fn share_transfer_verdict(
        &self,
        local_candidate_type: String,
        remote_candidate_type: String,
        total_bytes: u64,
        consent_granted: bool,
    ) -> ShareVerdictDto {
        self.inner.blocking_read().share_transfer_verdict(
            &local_candidate_type,
            &remote_candidate_type,
            total_bytes,
            consent_granted,
        )
    }

    /// How many chunks may go into a data channel currently holding
    /// `buffered_bytes`. Zero means wait for the drain event rather than poll.
    pub fn share_chunks_to_send(&self, buffered_bytes: u64) -> u32 {
        self.inner
            .blocking_read()
            .share_chunks_to_send(buffered_bytes)
    }

    /// `signal` crosses as the real [`CallSignal`] enum, not a JSON blob —
    /// only this crate still round-trips it through JSON internally, since
    /// that's the wire format `comrade_ui::ComradeRuntime::send_call_signal`
    /// puts on the encrypted DM channel.
    ///
    /// See [`Comrade::broadcast_chitthi`]'s doc comment for the lock discipline.
    pub async fn send_call_signal(
        &self,
        peer: String,
        call_id: String,
        media: CallMediaKind,
        signal: CallSignal,
    ) -> Result<(), UiError> {
        let signal_json =
            serde_json::to_string(&signal).map_err(|e| UiError::Engine(e.to_string()))?;
        let handles = self.inner.read().await.handles();
        handles
            .send_call_signal(&peer, &call_id, media.as_str(), &signal_json)
            .await
    }

    /// See [`Comrade::broadcast_chitthi`]'s doc comment for the lock discipline.
    pub async fn hangup_call(
        &self,
        peer: String,
        call_id: String,
        media: CallMediaKind,
        reason: HangupReason,
    ) -> Result<(), UiError> {
        let handles = self.inner.read().await.handles();
        handles
            .hangup_call(&peer, &call_id, media.as_str(), reason.as_str())
            .await
    }

    #[allow(clippy::too_many_arguments)]
    pub fn log_call(
        &self,
        peer: String,
        call_id: String,
        media: CallMediaKind,
        incoming: bool,
        outcome: String,
        started_at: u64,
        duration_secs: u64,
    ) -> Result<CallRecordDto, UiError> {
        self.inner.blocking_read().log_call(
            &peer,
            &call_id,
            media.as_str(),
            incoming,
            &outcome,
            started_at,
            duration_secs,
        )
    }

    pub fn call_history(&self, peer: Option<String>) -> Result<Vec<CallRecordDto>, UiError> {
        self.inner.blocking_read().call_history(peer.as_deref())
    }

    // ── Encrypted media (NIP-94/96 · Blossom) ───────────────────────────────

    /// `bytes` crosses as a native byte array — uniffi handles `Vec<u8>`
    /// directly, so the base64 encode/decode the old JNI bridge needed
    /// (Kotlin `String` was the only wire type available) is gone.
    ///
    /// See [`Comrade::broadcast_chitthi`]'s doc comment for the lock discipline.
    pub async fn upload_and_send_media(
        &self,
        target_pubkey: String,
        bytes: Vec<u8>,
        mime_type: String,
        caption: String,
    ) -> Result<MediaMessageDto, UiError> {
        let handles = self.inner.read().await.handles();
        handles
            .upload_and_send_media(&target_pubkey, bytes, &mime_type, &caption)
            .await
    }

    /// See [`Comrade::broadcast_chitthi`]'s doc comment for the lock discipline.
    pub async fn download_and_decrypt_media(
        &self,
        event_id: String,
    ) -> Result<MediaBytesDto, UiError> {
        let handles = self.inner.read().await.handles();
        handles.download_and_decrypt_media(&event_id).await
    }

    // ── Sakha/Sakhi CRDT ledger ──────────────────────────────────────────────

    /// See [`Comrade::broadcast_chitthi`]'s doc comment for the lock discipline.
    pub async fn sync_ledger(&self) -> Result<String, UiError> {
        let handles = self.inner.read().await.handles();
        handles.sync_ledger().await
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────
//
// The generated `extern "C"` scaffolding needs a foreign runtime (Kotlin/JNA)
// to exercise, but every function/method above is still plain Rust under
// that scaffolding — test it directly, the same way `comrade_ui`'s own tests
// drive `ComradeRuntime` without a JNI/Tauri host in the loop.

#[cfg(test)]
mod tests {
    use super::*;

    /// A `Comrade` over a runtime of its own.
    ///
    /// `Comrade::new()` now hands back the *process-global* runtime, and
    /// `cargo test` runs every test in one process on many threads — so a test
    /// that unlocks a vault, toggles a workspace or asserts "nothing is
    /// unlocked yet" needs its own runtime or it races every other test (and,
    /// for the unlock tests, would collide on redb's exclusive lock). Tests
    /// that are specifically *about* the shared global say so in their name
    /// and use `Comrade::new()`.
    fn isolated() -> Arc<Comrade> {
        Comrade::with_runtime(Arc::new(RwLock::new(ComradeRuntime::new())))
    }

    #[test]
    fn version_matches_crate_version() {
        assert_eq!(version(), env!("CARGO_PKG_VERSION"));
    }

    #[test]
    fn generate_keypair_produces_valid_bech32() {
        let kp = generate_keypair().expect("keygen must not fail");
        assert!(kp.npub.starts_with("npub1"));
        assert!(kp.nsec.starts_with("nsec1"));
    }

    #[test]
    fn npub_from_nsec_round_trips_and_rejects_garbage() {
        let kp = generate_keypair().unwrap();
        assert_eq!(npub_from_nsec(kp.nsec), Some(kp.npub));
        assert_eq!(npub_from_nsec("not an nsec".to_string()), None);
    }

    #[test]
    fn workspace_label_known_and_unknown_keys() {
        assert!(workspace_label("Base".to_string()).is_some());
        assert_eq!(workspace_label("NotAWorkspace".to_string()), None);
    }

    #[test]
    fn all_workspaces_lists_every_workspace_with_labels() {
        let list = all_workspaces();
        assert_eq!(list.len(), AppWorkspace::all().len());
        assert!(list.iter().any(|w| w.key == "Base"));
        for w in &list {
            assert!(!w.key.is_empty());
            assert!(!w.label.is_empty());
        }
    }

    // Plain (non-async) `#[test]`s for the sync tier — these must run with NO
    // ambient Tokio runtime, exactly like a real call from a JNA/native
    // thread: `blocking_read`/`blocking_write` panic if called from inside
    // one (see `tokio::sync::RwLock::blocking_read` docs), so exercising them
    // under `#[tokio::test]` would fail for a reason that says nothing about
    // this crate's own correctness.

    #[test]
    fn comrade_starts_locked_on_the_base_workspace() {
        let c = isolated();
        assert!(!c.is_vault_unlocked());
        assert!(!c.is_store_unlocked());
        assert_eq!(c.current_workspace().key, "Base");
    }

    #[test]
    fn new_with_relays_is_reachable_through_the_ffi_constructor() {
        // Reachable, and — like every other foreign constructor — a handle
        // onto the one process-global runtime, not a second one.
        let c = Comrade::new_with_relays(vec!["wss://relay.example.test".to_string()]);
        assert!(Arc::ptr_eq(&c.inner, global_runtime()));
        assert_eq!(c.current_workspace().key, "Base");
    }

    #[test]
    fn every_uniffi_handle_shares_one_process_global_runtime() {
        // The architectural invariant this crate exists to hold: two cdylibs
        // (or two runtimes in one) would both open the same vault directory,
        // and redb's exclusive lock makes the second open fail. See the
        // module header.
        let a = Comrade::new();
        let b = Comrade::new();
        assert!(Arc::ptr_eq(&a.inner, &b.inner));
        assert!(Arc::ptr_eq(&a.inner, global_runtime()));
        // …and the flutter_rust_bridge ABI resolves to the very same handle.
        assert!(Arc::ptr_eq(&a.inner, api::runtime()));
    }

    #[test]
    fn sync_calls_reject_gracefully_before_unlock() {
        // Mirrors comrade_ui::runtime::tests::commands_reject_gracefully_when_vault_locked
        // — this wrapper must not panic or silently succeed pre-unlock.
        let c = isolated();
        assert!(matches!(c.conversations(), Err(UiError::VaultLocked)));
        assert!(matches!(c.profile(), Err(UiError::NoIdentity)));
        assert!(matches!(c.comrades(), Err(UiError::VaultLocked)));
        assert!(matches!(
            c.peer_presence("npub1x".to_string()),
            Err(UiError::VaultLocked)
        ));
    }

    #[test]
    fn attention_calls_reject_gracefully_before_unlock() {
        // Same contract as `sync_calls_reject_gracefully_before_unlock`: the
        // Kotlin shell reads these from screens that can render before the
        // vault is open, so they must fail closed rather than panic.
        let c = isolated();
        assert!(matches!(c.attention_days(), Err(UiError::VaultLocked)));
        assert!(matches!(
            c.attention_summary("2026-07-31".to_string()),
            Err(UiError::VaultLocked)
        ));
        assert!(matches!(c.doom_apps(), Err(UiError::VaultLocked)));
        assert!(matches!(
            c.active_focus_session(),
            Err(UiError::VaultLocked)
        ));
        assert!(matches!(c.focus_sessions(), Err(UiError::VaultLocked)));
        assert!(matches!(
            c.suggested_focus_minutes(),
            Err(UiError::VaultLocked)
        ));
        assert!(matches!(c.reading(), Err(UiError::VaultLocked)));
        // …except the preset list, which a locked frontend still needs in
        // order to draw its own duration chips.
        assert!(!c.focus_presets().is_empty());
    }

    #[test]
    fn attention_lifecycle_is_reachable_through_the_ffi_object() {
        // The FFI surface is thin, but "thin" has been wrong before — drive
        // one full record → summarise → focus → read round trip through the
        // exported methods, on a plain thread with no ambient reactor (exactly
        // how JNA calls them).
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().to_string_lossy().to_string();
        let c = isolated();
        let rt = tokio::runtime::Runtime::new().unwrap();
        rt.block_on(c.unlock_vault(path, "pin".to_string()))
            .unwrap();

        let day = c
            .record_attention_day("2026-07-31".to_string(), 120, 55, 40)
            .unwrap();
        assert_eq!(day.screen_minutes, 120);
        assert_eq!(c.attention_days().unwrap().len(), 1);
        let summary = c.attention_summary("2026-07-31".to_string()).unwrap();
        assert_eq!(summary.today.unwrap().doom_minutes, 40);

        assert_eq!(
            c.set_doom_apps(vec!["com.example.feed".to_string()])
                .unwrap(),
            vec!["com.example.feed".to_string()]
        );
        assert_eq!(c.doom_apps().unwrap().len(), 1);

        assert_eq!(c.suggested_focus_minutes().unwrap(), 25);
        assert!(!c.focus_prompt().unwrap().is_empty());
        let started = c
            .start_focus_session("write the thing".to_string(), 25)
            .unwrap();
        assert_eq!(
            c.active_focus_session().unwrap().map(|s| s.id),
            Some(started.id)
        );
        let done = c.finish_focus_session(true).unwrap().unwrap();
        assert_eq!(done.outcome.as_deref(), Some("completed"));
        // Which of the rotating completion lines comes back depends on how
        // many sessions are stored (pinned in `comrade_core::attention`); what
        // matters here is that the outcome reaches the engine and an unknown
        // one is refused rather than guessed at.
        assert!(!c
            .focus_reflection("completed".to_string())
            .unwrap()
            .is_empty());
        assert!(matches!(
            c.focus_reflection("finished-ish".to_string()),
            Err(UiError::Engine(_))
        ));

        let saved = c
            .save_reading("Essay".to_string(), "A line worth reading.".to_string())
            .unwrap();
        assert_eq!(saved.chunks.concat(), "A line worth reading.");
        assert_eq!(c.set_reading_position(0).unwrap().unwrap().position, 0);
        assert!(c.clear_reading().unwrap());
        assert!(c.reading().unwrap().is_none());
    }

    #[tokio::test]
    async fn announcing_presence_before_unlock_is_a_quiet_zero_not_an_error() {
        // Presence is a courtesy, never an error path — the Android shell
        // calls this on every foreground transition, including ones that
        // race the vault being open.
        //
        // `isolated()`, not `Comrade::new()`: this asserts a *locked*
        // precondition, and the process-global vault is unlocked partway
        // through the run by
        // `a_vault_unlocked_through_the_dart_abi_is_visible_through_the_kotlin_abi`
        // — the one test that owns the global's lifecycle. Sharing the global
        // here made this fail roughly one run in four (`set_comrade` returning
        // `Ok` because the vault had just been opened underneath it), which is
        // exactly what the note above that test warns about.
        let c = isolated();
        assert_eq!(c.announce_presence(true).await, 0);
        assert!(matches!(
            c.set_comrade("npub1x".to_string(), true).await,
            Err(UiError::VaultLocked)
        ));
    }

    #[test]
    fn call_sas_needs_no_unlock_and_is_order_independent() {
        // Pure computation over the two SDP strings already in hand — unlike
        // the store-backed calls above, this must work before the vault is
        // ever unlocked.
        let c = isolated();
        let sdp_a = "v=0\r\na=fingerprint:sha-256 AA:BB\r\n".to_string();
        let sdp_b = "v=0\r\na=fingerprint:sha-256 CC:DD\r\n".to_string();
        let sas = c.call_sas(sdp_a.clone(), sdp_b.clone());
        assert_eq!(sas.as_ref().map(Vec::len), Some(4));
        assert_eq!(sas, c.call_sas(sdp_b, sdp_a));
    }

    // `#[tokio::test]` for the async tier — these run under
    // `async_runtime = "tokio"`'s real calling convention (an active
    // reactor), same as the sync tests above run under none.

    #[tokio::test]
    async fn async_calls_reject_gracefully_before_unlock() {
        let c = isolated();
        assert!(matches!(
            c.send_call_signal(
                "peer".to_string(),
                "call1".to_string(),
                CallMediaKind::Audio,
                CallSignal::Ringing,
            )
            .await,
            Err(UiError::VaultLocked)
        ));
    }

    #[test]
    fn lock_vault_is_reachable_through_the_ffi_object_and_is_idempotent() {
        // A plain (non-async) `#[test]`, like `comrade_starts_locked_on_the_base_workspace`
        // above: `is_vault_unlocked`/`profile` go through `blocking_read`, which
        // panics if called from inside an ambient Tokio runtime (i.e. under
        // `#[tokio::test]`) — see that test's doc comment. The async methods
        // (`unlock_vault`/`lock_vault`) instead run on a runtime built and
        // driven by hand via `block_on`, exactly like a real JNA/native caller
        // would (there is no surrounding reactor on that thread either).
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().to_string_lossy().to_string();
        let c = isolated();
        let rt = tokio::runtime::Runtime::new().unwrap();

        rt.block_on(c.unlock_vault(path.clone(), "pin".to_string()))
            .unwrap();
        assert!(c.is_vault_unlocked());

        rt.block_on(c.lock_vault());
        assert!(!c.is_vault_unlocked());
        assert!(matches!(c.profile(), Err(UiError::NoIdentity)));

        // Idempotent — locking an already-locked runtime must not panic.
        rt.block_on(c.lock_vault());
        assert!(!c.is_vault_unlocked());

        // Unlocking again resumes normally.
        rt.block_on(c.unlock_vault(path, "pin".to_string()))
            .unwrap();
        assert!(c.is_vault_unlocked());
    }

    #[test]
    fn turn_server_status_is_reachable_through_the_ffi_object() {
        let c = isolated();
        // Pre-unlock: honest "nothing configured", not an error.
        let status = c.turn_server_status();
        assert!(!status.configured);
        assert_eq!(status.url, None);
    }

    #[tokio::test]
    async fn event_listener_registration_is_idempotent() {
        #[derive(Default)]
        struct Counter(std::sync::atomic::AtomicUsize);
        impl BridgeEventListener for Counter {
            fn on_event(&self, _event: BridgeEvent) {
                self.0.fetch_add(1, Ordering::SeqCst);
            }
        }

        let c = isolated();
        let listener: Arc<dyn BridgeEventListener> = Arc::new(Counter::default());
        c.set_event_listener(listener.clone()).await;
        // A second registration must be a no-op, not a second forwarder task.
        c.set_event_listener(listener).await;
        assert!(c.listener_registered.load(Ordering::SeqCst));
    }

    #[tokio::test]
    async fn listener_can_synchronously_call_a_blocking_read_method_from_on_event() {
        // Regression guard for the module-header invariant: `on_event` runs
        // on the dedicated listener thread, never a Tokio worker, so a
        // Kotlin listener that re-enters a sync (`blocking_read`) method from
        // inside its callback must never panic. Before this fix the forwarder
        // called `on_event` from a `tokio::spawn`ed task, where `blocking_read`
        // panics unconditionally.
        struct ReentrantListener {
            comrade: Arc<Comrade>,
            called: Arc<AtomicBool>,
            panicked: Arc<AtomicBool>,
        }
        impl BridgeEventListener for ReentrantListener {
            fn on_event(&self, _event: BridgeEvent) {
                let outcome = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    self.comrade.workspaces();
                }));
                self.called.store(true, Ordering::SeqCst);
                if outcome.is_err() {
                    self.panicked.store(true, Ordering::SeqCst);
                }
            }
        }

        let c = isolated();
        let called = Arc::new(AtomicBool::new(false));
        let panicked = Arc::new(AtomicBool::new(false));
        let listener: Arc<dyn BridgeEventListener> = Arc::new(ReentrantListener {
            comrade: c.clone(),
            called: called.clone(),
            panicked: panicked.clone(),
        });
        c.set_event_listener(listener).await;

        c.inner
            .read()
            .await
            .event_sender()
            .send(BridgeEvent::MeshStatusChanged(MeshStatusDto {
                active: false,
                peer_count: 0,
            }))
            .unwrap();

        for _ in 0..100 {
            if called.load(Ordering::SeqCst) {
                break;
            }
            tokio::time::sleep(std::time::Duration::from_millis(20)).await;
        }
        assert!(
            called.load(Ordering::SeqCst),
            "the dedicated listener thread must have delivered the event"
        );
        assert!(
            !panicked.load(Ordering::SeqCst),
            "on_event must be able to call a blocking_read method with no panic"
        );
    }

    // ── The Dart (flutter_rust_bridge) ABI ────────────────────────────────

    #[test]
    fn dart_sync_tier_is_safe_on_a_plain_thread_with_no_reactor() {
        // FRB dispatches a non-`async fn` through `SimpleExecutor::execute_normal`
        // onto a `SimpleThreadPool` (`threadpool::ThreadPool` — plain std
        // threads, no ambient Tokio reactor). That is the *only* reason the
        // sync tier of `api` may use `blocking_read`/`blocking_write`, which
        // panic inside a reactor. Reproduce that calling convention here
        // rather than trusting it: if someone later makes one of these
        // functions async-aware, or FRB changes its executor, this fails.
        let joined = std::thread::spawn(|| {
            assert_eq!(api::current_workspace().key, "Base");
            let _ = api::workspaces();
            let _ = api::mesh_status();
            let _ = api::conversations();
            let _ = api::message_requests();
            let _ = api::list_contacts();
            let _ = api::comrades();
            let _ = api::peer_presence("npub1x".to_string());
            let _ = api::outbox_pending();
            let _ = api::metrics_snapshot();
            let _ = api::journal_entries();
            let _ = api::tara_crisis_resources();
            let _ = api::turn_server_status();
            let _ = api::call_ice_servers();
            let _ = api::call_sas("v=0\r\n".to_string(), "v=0\r\n".to_string());
            api::version()
        })
        .join();
        assert_eq!(
            joined.expect("the Dart sync tier must not panic off-reactor"),
            env!("CARGO_PKG_VERSION")
        );
    }

    #[tokio::test]
    async fn dart_event_pump_merges_both_channels_and_stops_when_dart_drops() {
        // The fan-in half of `api::bridge_event_stream`. A real `StreamSink`
        // needs a live Dart isolate port, so the sink is stubbed; what is
        // under test is that *both* buses reach one consumer and that a dead
        // consumer ends the task instead of spinning.
        let (critical_tx, critical_rx) = tokio::sync::broadcast::channel(8);
        let (feed_tx, feed_rx) = tokio::sync::broadcast::channel(8);

        let mesh = BridgeEvent::MeshStatusChanged(MeshStatusDto {
            active: true,
            peer_count: 3,
        });
        let ledger = BridgeEvent::LedgerUpdated {
            ledger: "from the feed bus".to_string(),
        };
        critical_tx.send(mesh.clone()).unwrap();
        feed_tx.send(ledger.clone()).unwrap();

        let (seen_tx, mut seen_rx) = tokio::sync::mpsc::unbounded_channel();
        // Accept exactly two events, then report the consumer as gone.
        let mut budget = 2;
        let pump = tokio::spawn(async move {
            api::pump_bridge_events(critical_rx, feed_rx, move |event| {
                seen_tx.send(event).unwrap();
                budget -= 1;
                budget > 0
            })
            .await;
        });

        let mut seen = Vec::new();
        for _ in 0..2 {
            seen.push(
                tokio::time::timeout(std::time::Duration::from_secs(5), seen_rx.recv())
                    .await
                    .expect("the pump must forward both buses")
                    .expect("sender must stay alive"),
            );
        }
        assert!(seen.contains(&mesh), "critical bus event missing");
        assert!(seen.contains(&ledger), "feed bus event missing");

        // A consumer that has gone away must end the task, not spin forever.
        tokio::time::timeout(std::time::Duration::from_secs(5), pump)
            .await
            .expect("the pump must exit once the Dart sink is gone")
            .unwrap();
    }

    #[tokio::test]
    async fn one_event_reaches_the_kotlin_listener_and_the_dart_stream_at_once() {
        // Requirement: both consumers work *simultaneously* off one runtime.
        // `broadcast` fans out, so neither starves the other — but that only
        // holds if the Dart pump and the uniffi forwarder subscribe to the
        // same `ComradeRuntime`, which is what this asserts end to end.
        #[derive(Default)]
        struct Collect(std::sync::Mutex<Vec<BridgeEvent>>);
        impl BridgeEventListener for Collect {
            fn on_event(&self, event: BridgeEvent) {
                self.0.lock().unwrap().push(event);
            }
        }

        let c = isolated();
        let kotlin = Arc::new(Collect::default());
        c.set_event_listener(kotlin.clone()).await;

        let (critical_rx, feed_rx, sender) = {
            let guard = c.inner.read().await;
            (
                guard.subscribe_events(),
                guard.subscribe_feed_events(),
                guard.event_sender(),
            )
        };
        let (dart_tx, mut dart_rx) = tokio::sync::mpsc::unbounded_channel();
        tokio::spawn(async move {
            api::pump_bridge_events(critical_rx, feed_rx, move |event| {
                dart_tx.send(event).is_ok()
            })
            .await;
        });

        let event = BridgeEvent::LedgerUpdated {
            ledger: "shared bus".to_string(),
        };
        sender.send(event.clone()).unwrap();

        // Dart side.
        let via_dart = tokio::time::timeout(std::time::Duration::from_secs(5), dart_rx.recv())
            .await
            .expect("the Dart pump must receive the event")
            .expect("pump must stay alive");
        assert_eq!(via_dart, event);

        // Kotlin side — delivered on the dedicated forwarder thread, so poll.
        for _ in 0..250 {
            if !kotlin.0.lock().unwrap().is_empty() {
                break;
            }
            tokio::time::sleep(std::time::Duration::from_millis(20)).await;
        }
        assert_eq!(
            kotlin.0.lock().unwrap().as_slice(),
            std::slice::from_ref(&event),
            "the uniffi listener must receive the same event"
        );
    }

    // ── The dual-ABI invariant ────────────────────────────────────────────
    //
    // NOTE: this is the *only* test that unlocks the process-global vault.
    // Every other test above runs against an `isolated()` runtime precisely so
    // this one can own the global's lifecycle without racing them. If you add
    // a second global-mutating test, serialise the two.

    #[test]
    fn a_vault_unlocked_through_the_dart_abi_is_visible_through_the_kotlin_abi() {
        // The whole reason both ABIs live in one cdylib. `api::unlock_vault`
        // (flutter_rust_bridge → Dart) and `Comrade` (uniffi → Kotlin) must be
        // looking at one `ComradeRuntime`; if they were not, this second
        // "open" would be a second `redb::Database::create` on the same
        // directory and would fail on redb's exclusive lock instead of
        // reporting an already-unlocked vault.
        //
        // A plain `#[test]`: the uniffi assertions go through `blocking_read`,
        // which panics inside an ambient reactor. The async halves run on a
        // hand-built runtime via `block_on`, exactly like a real foreign
        // caller with no surrounding reactor.
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().to_string_lossy().to_string();
        let rt = tokio::runtime::Runtime::new().unwrap();

        let via_dart = rt
            .block_on(api::unlock_vault(path.clone(), "pin".to_string()))
            .expect("unlock through the Dart ABI must succeed");

        let via_kotlin = Comrade::new();
        assert!(via_kotlin.is_vault_unlocked());
        assert_eq!(via_kotlin.current_identity(), Some(via_dart));

        // …and back the other way: lock through Kotlin, observe through Dart.
        rt.block_on(via_kotlin.lock_vault());
        assert!(!rt.block_on(api::is_vault_unlocked()));
    }
}
