// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `pump_bridge_events`, `runtime`

/// The comrade_jni crate version (e.g. "0.1.0").
String version() => RustLib.instance.api.crateApiVersion();

/// A freshly generated secp256k1 keypair, Bech32-encoded. Standalone — doesn't
/// touch the encrypted store; see [`generate_identity`] and [`unlock_vault`]
/// for the store-backed identity flow every UI screen actually drives.
KeypairDto generateKeypair() => RustLib.instance.api.crateApiGenerateKeypair();

/// Derive the npub from an nsec Bech32 string, or `None` if it doesn't parse.
String? npubFromNsec({required String nsec}) =>
    RustLib.instance.api.crateApiNpubFromNsec(nsec: nsec);

/// The display label for a workspace discriminant, or `None` for an unknown key.
String? workspaceLabel({required String workspace}) =>
    RustLib.instance.api.crateApiWorkspaceLabel(workspace: workspace);

/// Every workspace discriminant and its label — a stable, store-free list
/// (contrast [`workspaces`], which also reports which one is active).
List<WorkspaceKeyLabel> allWorkspaces() =>
    RustLib.instance.api.crateApiAllWorkspaces();

/// Materialise the process-global runtime, if some other caller (e.g. Kotlin
/// constructing `Comrade()`) has not already. The Dart counterpart of
/// `Comrade()`; there is no handle to hold onto because there is nothing to
/// hold — every function below finds the same runtime on its own.
Future<void> initRuntime() => RustLib.instance.api.crateApiInitRuntime();

/// [`init_runtime`], but seeding the runtime with an explicit relay set —
/// AUDIT.md COMMS-03's isolated-relay test hook. Only takes effect if this is
/// what first creates the runtime; the shipping app calls [`init_runtime`].
Future<void> initRuntimeWithRelays({required List<String> relays}) =>
    RustLib.instance.api.crateApiInitRuntimeWithRelays(relays: relays);

/// Open the encrypted store, restore or seed the identity, build the engines,
/// and start the background feed/DM loops. Safe to call more than once
/// (returns the already-loaded identity) — including when the *other* ABI
/// already unlocked it, which is the whole point of the shared runtime.
Future<IdentityDto> unlockVault(
        {required String path, required String passphrase}) =>
    RustLib.instance.api
        .crateApiUnlockVault(path: path, passphrase: passphrase);

Future<bool> isVaultUnlocked() =>
    RustLib.instance.api.crateApiIsVaultUnlocked();

Future<bool> isStoreUnlocked() =>
    RustLib.instance.api.crateApiIsStoreUnlocked();

/// Re-lock the vault: abort the background feed/DM/sakha loops and drop the
/// store, engines, and in-memory identity.
Future<void> lockVault() => RustLib.instance.api.crateApiLockVault();

Future<IdentityDto> generateIdentity() =>
    RustLib.instance.api.crateApiGenerateIdentity();

Future<IdentityDto?> currentIdentity() =>
    RustLib.instance.api.crateApiCurrentIdentity();

Future<List<UpiIntentDto>> extractPayments({required String text}) =>
    RustLib.instance.api.crateApiExtractPayments(text: text);

Future<List<WorkspaceDto>> workspaces() =>
    RustLib.instance.api.crateApiWorkspaces();

Future<WorkspaceDto> currentWorkspace() =>
    RustLib.instance.api.crateApiCurrentWorkspace();

/// Async because switching also starts/stops the Saathi mesh engine to match.
Future<WorkspaceDto> toggleWorkspace({required String target}) =>
    RustLib.instance.api.crateApiToggleWorkspace(target: target);

/// Async for the same reason as [`toggle_workspace`].
Future<WorkspaceDto> back() => RustLib.instance.api.crateApiBack();

/// Snapshot of the off-grid Saathi mesh's live status, for seeding a
/// connectivity indicator before the first `BridgeEvent::MeshStatusChanged`
/// arrives. Never fails: the mesh being off is a valid, common state.
Future<MeshStatusDto> meshStatus() => RustLib.instance.api.crateApiMeshStatus();

Future<List<ChitthiDto>> fetchSabhaTimeline() =>
    RustLib.instance.api.crateApiFetchSabhaTimeline();

/// Takes a cheap, synchronous handle snapshot under the guard and runs the
/// relay round-trip after it is dropped — AUDIT P2: never hold the runtime
/// lock across a network await, or one slow relay stalls every other call.
Future<String> broadcastChitthi({required String content, String? replyTo}) =>
    RustLib.instance.api
        .crateApiBroadcastChitthi(content: content, replyTo: replyTo);

/// See [`broadcast_chitthi`] for the lock discipline.
Future<MessageDto> sendDm({required String target, required String content}) =>
    RustLib.instance.api.crateApiSendDm(target: target, content: content);

/// See [`broadcast_chitthi`] for the lock discipline.
Future<MessageDto> sendDmReply(
        {required String target, required String content, String? replyTo}) =>
    RustLib.instance.api.crateApiSendDmReply(
        target: target, content: content, replyTo: replyTo);

Future<List<ConversationDto>> conversations() =>
    RustLib.instance.api.crateApiConversations();

Future<List<MessageDto>> messagesWith({required String peer}) =>
    RustLib.instance.api.crateApiMessagesWith(peer: peer);

/// Full encrypted-media history with `peer`, oldest first — the media
/// counterpart of [`messages_with`].
Future<List<MediaMessageDto>> mediaWith({required String peer}) =>
    RustLib.instance.api.crateApiMediaWith(peer: peer);

Future<List<MessageRequestDto>> messageRequests() =>
    RustLib.instance.api.crateApiMessageRequests();

/// Async because accepting fires a background profile-share + receipt send
/// that needs a live reactor to `tokio::spawn` onto.
Future<void> acceptRequest({required String peer}) =>
    RustLib.instance.api.crateApiAcceptRequest(peer: peer);

Future<void> blockConversation({required String peer}) =>
    RustLib.instance.api.crateApiBlockConversation(peer: peer);

/// Async for the same reason as [`accept_request`].
Future<void> markConversationRead({required String peer}) =>
    RustLib.instance.api.crateApiMarkConversationRead(peer: peer);

Future<ProfileDto> profile() => RustLib.instance.api.crateApiProfile();

Future<ProfileDto> setUsername({required String name}) =>
    RustLib.instance.api.crateApiSetUsername(name: name);

Future<ContactDto> addContact({required String npub, required String alias}) =>
    RustLib.instance.api.crateApiAddContact(npub: npub, alias: alias);

Future<ContactDto> setContactAlias(
        {required String npub, required String alias}) =>
    RustLib.instance.api.crateApiSetContactAlias(npub: npub, alias: alias);

Future<bool> removeContact({required String npub}) =>
    RustLib.instance.api.crateApiRemoveContact(npub: npub);

Future<List<ContactDto>> listContacts() =>
    RustLib.instance.api.crateApiListContacts();

/// See [`broadcast_chitthi`] for the lock discipline.
Future<List<FoundProfileDto>> searchProfiles({required String query}) =>
    RustLib.instance.api.crateApiSearchProfiles(query: query);

/// Detaches the refresher and drops the shared lock before the relay
/// round-trip (AUDIT P2).
Future<BigInt> refreshPeerProfiles() =>
    RustLib.instance.api.crateApiRefreshPeerProfiles();

Future<JournalEntryDto> addJournalEntry({required String text, String? mood}) =>
    RustLib.instance.api.crateApiAddJournalEntry(text: text, mood: mood);

Future<List<JournalEntryDto>> journalEntries() =>
    RustLib.instance.api.crateApiJournalEntries();

Future<bool> deleteJournalEntry({required String id}) =>
    RustLib.instance.api.crateApiDeleteJournalEntry(id: id);

/// Persist the user's message, compute Tara's on-device reply, persist and
/// return it. `crisis == true` on the reply means the UI must surface
/// [`tara_crisis_resources`] with it.
Future<TaraMessageDto> taraSend({required String text}) =>
    RustLib.instance.api.crateApiTaraSend(text: text);

/// The whole Tara thread, oldest-first (chat order).
Future<List<TaraMessageDto>> taraThread() =>
    RustLib.instance.api.crateApiTaraThread();

/// Delete the entire Tara thread; returns how many turns were removed.
Future<BigInt> clearTaraThread() =>
    RustLib.instance.api.crateApiClearTaraThread();

/// The opener shown while the thread is empty — shaped by recent journal mood
/// markers only, never entry text.
Future<String> taraOpener() => RustLib.instance.api.crateApiTaraOpener();

/// The crisis helplines Tara hands off to.
Future<List<CrisisResourceDto>> taraCrisisResources() =>
    RustLib.instance.api.crateApiTaraCrisisResources();

Future<List<IceServerDto>> callIceServers() =>
    RustLib.instance.api.crateApiCallIceServers();

Future<List<IceServerDto>> callIceServersFor({required IceStrategy strategy}) =>
    RustLib.instance.api.crateApiCallIceServersFor(strategy: strategy);

/// The 4-emoji short authentication string (SAS) for the in-progress call
/// whose local/remote SDPs are `local_sdp`/`remote_sdp`. `None` when either
/// side's SDP carries no `a=fingerprint:` line to derive a code from.
Future<List<String>?> callSas(
        {required String localSdp, required String remoteSdp}) =>
    RustLib.instance.api
        .crateApiCallSas(localSdp: localSdp, remoteSdp: remoteSdp);

Future<void> setTurnServer(
        {required String url,
        required String username,
        required String credential}) =>
    RustLib.instance.api.crateApiSetTurnServer(
        url: url, username: username, credential: credential);

/// The "is a relay configured" diagnostic status. Carries the URL only; never
/// the username/credential.
Future<TurnServerStatusDto> turnServerStatus() =>
    RustLib.instance.api.crateApiTurnServerStatus();

Future<CallSessionDto> placeCall(
        {required String peer, required CallMediaKind media}) =>
    RustLib.instance.api.crateApiPlaceCall(peer: peer, media: media);

/// `signal` crosses as the real [`CallSignal`] enum, not a JSON blob — only
/// this crate still round-trips it through JSON internally, since that's the
/// wire format the encrypted DM channel carries.
///
/// See [`broadcast_chitthi`] for the lock discipline.
Future<void> sendCallSignal(
        {required String peer,
        required String callId,
        required CallMediaKind media,
        required CallSignal signal}) =>
    RustLib.instance.api.crateApiSendCallSignal(
        peer: peer, callId: callId, media: media, signal: signal);

/// See [`broadcast_chitthi`] for the lock discipline.
Future<void> hangupCall(
        {required String peer,
        required String callId,
        required CallMediaKind media,
        required HangupReason reason}) =>
    RustLib.instance.api.crateApiHangupCall(
        peer: peer, callId: callId, media: media, reason: reason);

Future<CallRecordDto> logCall(
        {required String peer,
        required String callId,
        required CallMediaKind media,
        required bool incoming,
        required String outcome,
        required BigInt startedAt,
        required BigInt durationSecs}) =>
    RustLib.instance.api.crateApiLogCall(
        peer: peer,
        callId: callId,
        media: media,
        incoming: incoming,
        outcome: outcome,
        startedAt: startedAt,
        durationSecs: durationSecs);

Future<List<CallRecordDto>> callHistory({String? peer}) =>
    RustLib.instance.api.crateApiCallHistory(peer: peer);

/// `bytes` crosses as a native byte array.
///
/// See [`broadcast_chitthi`] for the lock discipline.
Future<MediaMessageDto> uploadAndSendMedia(
        {required String targetPubkey,
        required List<int> bytes,
        required String mimeType,
        required String caption}) =>
    RustLib.instance.api.crateApiUploadAndSendMedia(
        targetPubkey: targetPubkey,
        bytes: bytes,
        mimeType: mimeType,
        caption: caption);

/// See [`broadcast_chitthi`] for the lock discipline.
Future<MediaBytesDto> downloadAndDecryptMedia({required String eventId}) =>
    RustLib.instance.api.crateApiDownloadAndDecryptMedia(eventId: eventId);

/// See [`broadcast_chitthi`] for the lock discipline.
Future<String> syncLedger() => RustLib.instance.api.crateApiSyncLedger();

/// Every [`BridgeEvent`], as a Dart `Stream`.
///
/// The Dart counterpart of `Comrade::set_event_listener`, and deliberately
/// sourced from the *same* two `tokio::sync::broadcast` channels the uniffi
/// listener forwards — `broadcast` fans out to every receiver, so a Kotlin
/// service listening through uniffi and a Flutter UI listening through this
/// stream both see every event, simultaneously, with neither starving the
/// other.
///
/// Two channels are merged, exactly as `set_event_listener` forwards two:
/// the critical stream (DMs, requests, call signals, mesh/ledger updates) and
/// the separate, small, deliberately-lossy `IncomingChitthi` feed stream (see
/// `comrade_ui::ComradeRuntime::subscribe_feed_events`, AUDIT.md COMMS-04), so
/// a public-feed flood can never delay a call signal queued behind it.
///
/// Subscribing late is safe but not retroactive: `broadcast` receivers only
/// see events sent after they subscribe, so call this before [`unlock_vault`].
/// Dropping the Dart subscription ends the task.
Stream<BridgeEvent> bridgeEventStream() =>
    RustLib.instance.api.crateApiBridgeEventStream();

@freezed
sealed class BridgeEvent with _$BridgeEvent {
  const BridgeEvent._();

  const factory BridgeEvent.incomingChitthi(
    ChitthiDto field0,
  ) = BridgeEvent_IncomingChitthi;
  const factory BridgeEvent.incomingDirectMessage(
    DirectMessageDto field0,
  ) = BridgeEvent_IncomingDirectMessage;
  const factory BridgeEvent.incomingMedia(
    MediaMessageDto field0,
  ) = BridgeEvent_IncomingMedia;
  const factory BridgeEvent.incomingCallSignal(
    CallSignalDto field0,
  ) = BridgeEvent_IncomingCallSignal;
  const factory BridgeEvent.incomingMessageRequest(
    MessageRequestDto field0,
  ) = BridgeEvent_IncomingMessageRequest;
  const factory BridgeEvent.messageStatus({
    required String peer,
    required List<String> messageIds,
    required String status,
  }) = BridgeEvent_MessageStatus;
  const factory BridgeEvent.peerProfileUpdated({
    required String peer,
    String? name,
  }) = BridgeEvent_PeerProfileUpdated;
  const factory BridgeEvent.meshStatusChanged(
    MeshStatusDto field0,
  ) = BridgeEvent_MeshStatusChanged;
  const factory BridgeEvent.ledgerUpdated({
    required String ledger,
  }) = BridgeEvent_LedgerUpdated;
}

enum CallMediaKind {
  audio,
  video,
  ;
}

class CallRecordDto {
  final String id;
  final String peer;
  final String media;
  final bool incoming;
  final String outcome;
  final BigInt startedAt;
  final BigInt durationSecs;

  const CallRecordDto({
    required this.id,
    required this.peer,
    required this.media,
    required this.incoming,
    required this.outcome,
    required this.startedAt,
    required this.durationSecs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      peer.hashCode ^
      media.hashCode ^
      incoming.hashCode ^
      outcome.hashCode ^
      startedAt.hashCode ^
      durationSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallRecordDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          peer == other.peer &&
          media == other.media &&
          incoming == other.incoming &&
          outcome == other.outcome &&
          startedAt == other.startedAt &&
          durationSecs == other.durationSecs;
}

class CallSessionDto {
  final String callId;
  final String peer;
  final String media;
  final List<IceServerDto> iceServers;

  const CallSessionDto({
    required this.callId,
    required this.peer,
    required this.media,
    required this.iceServers,
  });

  @override
  int get hashCode =>
      callId.hashCode ^ peer.hashCode ^ media.hashCode ^ iceServers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallSessionDto &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          peer == other.peer &&
          media == other.media &&
          iceServers == other.iceServers;
}

@freezed
sealed class CallSignal with _$CallSignal {
  const CallSignal._();

  const factory CallSignal.offer({
    required String sdp,
  }) = CallSignal_Offer;
  const factory CallSignal.answer({
    required String sdp,
  }) = CallSignal_Answer;
  const factory CallSignal.ice({
    required String candidate,
    String? sdpMid,
    int? sdpMLineIndex,
  }) = CallSignal_Ice;
  const factory CallSignal.ringing() = CallSignal_Ringing;
  const factory CallSignal.busy() = CallSignal_Busy;
  const factory CallSignal.hangup({
    required HangupReason reason,
  }) = CallSignal_Hangup;
}

class CallSignalDto {
  final String callId;
  final String peer;
  final String media;
  final CallSignal signal;
  final BigInt createdAt;

  const CallSignalDto({
    required this.callId,
    required this.peer,
    required this.media,
    required this.signal,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      callId.hashCode ^
      peer.hashCode ^
      media.hashCode ^
      signal.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallSignalDto &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          peer == other.peer &&
          media == other.media &&
          signal == other.signal &&
          createdAt == other.createdAt;
}

class ChitthiDto {
  final String id;
  final String author;
  final String content;
  final BigInt createdAt;
  final String? replyTo;

  const ChitthiDto({
    required this.id,
    required this.author,
    required this.content,
    required this.createdAt,
    this.replyTo,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      author.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      replyTo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChitthiDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          author == other.author &&
          content == other.content &&
          createdAt == other.createdAt &&
          replyTo == other.replyTo;
}

class ContactDto {
  final String npub;
  final String alias;
  final String? name;

  const ContactDto({
    required this.npub,
    required this.alias,
    this.name,
  });

  @override
  int get hashCode => npub.hashCode ^ alias.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactDto &&
          runtimeType == other.runtimeType &&
          npub == other.npub &&
          alias == other.alias &&
          name == other.name;
}

class ConversationDto {
  final String peer;
  final String? alias;
  final String? peerName;
  final String lastMessage;
  final BigInt lastAt;
  final bool lastOutgoing;

  const ConversationDto({
    required this.peer,
    this.alias,
    this.peerName,
    required this.lastMessage,
    required this.lastAt,
    required this.lastOutgoing,
  });

  @override
  int get hashCode =>
      peer.hashCode ^
      alias.hashCode ^
      peerName.hashCode ^
      lastMessage.hashCode ^
      lastAt.hashCode ^
      lastOutgoing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationDto &&
          runtimeType == other.runtimeType &&
          peer == other.peer &&
          alias == other.alias &&
          peerName == other.peerName &&
          lastMessage == other.lastMessage &&
          lastAt == other.lastAt &&
          lastOutgoing == other.lastOutgoing;
}

class CrisisResourceDto {
  final String name;
  final String contact;
  final String note;

  const CrisisResourceDto({
    required this.name,
    required this.contact,
    required this.note,
  });

  @override
  int get hashCode => name.hashCode ^ contact.hashCode ^ note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrisisResourceDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          contact == other.contact &&
          note == other.note;
}

class DirectMessageDto {
  final String id;
  final String sender;
  final String content;
  final BigInt createdAt;
  final List<UpiIntentDto> upiIntents;
  final String? replyTo;

  const DirectMessageDto({
    required this.id,
    required this.sender,
    required this.content,
    required this.createdAt,
    required this.upiIntents,
    this.replyTo,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sender.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      upiIntents.hashCode ^
      replyTo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DirectMessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sender == other.sender &&
          content == other.content &&
          createdAt == other.createdAt &&
          upiIntents == other.upiIntents &&
          replyTo == other.replyTo;
}

class FoundProfileDto {
  final String npub;
  final String? name;
  final String? about;

  const FoundProfileDto({
    required this.npub,
    this.name,
    this.about,
  });

  @override
  int get hashCode => npub.hashCode ^ name.hashCode ^ about.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FoundProfileDto &&
          runtimeType == other.runtimeType &&
          npub == other.npub &&
          name == other.name &&
          about == other.about;
}

enum HangupReason {
  normal,
  declined,
  busy,
  missed,
  cancelled,
  failed,
  unknown,
  ;
}

class IceServerDto {
  final List<String> urls;
  final String? username;
  final String? credential;

  const IceServerDto({
    required this.urls,
    this.username,
    this.credential,
  });

  @override
  int get hashCode => urls.hashCode ^ username.hashCode ^ credential.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IceServerDto &&
          runtimeType == other.runtimeType &&
          urls == other.urls &&
          username == other.username &&
          credential == other.credential;
}

enum IceStrategy {
  stunOnly,
  stunAndTurn,
  ;
}

class IdentityDto {
  final String npub;
  final bool hasSecret;

  const IdentityDto({
    required this.npub,
    required this.hasSecret,
  });

  @override
  int get hashCode => npub.hashCode ^ hasSecret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityDto &&
          runtimeType == other.runtimeType &&
          npub == other.npub &&
          hasSecret == other.hasSecret;
}

class JournalEntryDto {
  final String id;
  final String text;
  final String? mood;
  final BigInt createdAt;

  const JournalEntryDto({
    required this.id,
    required this.text,
    this.mood,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ text.hashCode ^ mood.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JournalEntryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text &&
          mood == other.mood &&
          createdAt == other.createdAt;
}

class MediaBytesDto {
  final String mimeType;
  final String base64;

  const MediaBytesDto({
    required this.mimeType,
    required this.base64,
  });

  @override
  int get hashCode => mimeType.hashCode ^ base64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaBytesDto &&
          runtimeType == other.runtimeType &&
          mimeType == other.mimeType &&
          base64 == other.base64;
}

class MediaMessageDto {
  final String eventId;
  final String url;
  final String mimeType;
  final String caption;
  final String sender;
  final BigInt createdAt;
  final BigInt size;
  final bool outgoing;

  const MediaMessageDto({
    required this.eventId,
    required this.url,
    required this.mimeType,
    required this.caption,
    required this.sender,
    required this.createdAt,
    required this.size,
    required this.outgoing,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      url.hashCode ^
      mimeType.hashCode ^
      caption.hashCode ^
      sender.hashCode ^
      createdAt.hashCode ^
      size.hashCode ^
      outgoing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaMessageDto &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          url == other.url &&
          mimeType == other.mimeType &&
          caption == other.caption &&
          sender == other.sender &&
          createdAt == other.createdAt &&
          size == other.size &&
          outgoing == other.outgoing;
}

class MeshStatusDto {
  final bool active;
  final BigInt peerCount;

  const MeshStatusDto({
    required this.active,
    required this.peerCount,
  });

  @override
  int get hashCode => active.hashCode ^ peerCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeshStatusDto &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          peerCount == other.peerCount;
}

class MessageDto {
  final String id;
  final String peer;
  final String content;
  final BigInt createdAt;
  final bool outgoing;
  final String? status;
  final String? replyTo;

  const MessageDto({
    required this.id,
    required this.peer,
    required this.content,
    required this.createdAt,
    required this.outgoing,
    this.status,
    this.replyTo,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      peer.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      outgoing.hashCode ^
      status.hashCode ^
      replyTo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          peer == other.peer &&
          content == other.content &&
          createdAt == other.createdAt &&
          outgoing == other.outgoing &&
          status == other.status &&
          replyTo == other.replyTo;
}

class MessageRequestDto {
  final String peer;
  final String lastMessage;
  final BigInt lastAt;

  const MessageRequestDto({
    required this.peer,
    required this.lastMessage,
    required this.lastAt,
  });

  @override
  int get hashCode => peer.hashCode ^ lastMessage.hashCode ^ lastAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageRequestDto &&
          runtimeType == other.runtimeType &&
          peer == other.peer &&
          lastMessage == other.lastMessage &&
          lastAt == other.lastAt;
}

class ProfileDto {
  final String npub;
  final String? username;

  const ProfileDto({
    required this.npub,
    this.username,
  });

  @override
  int get hashCode => npub.hashCode ^ username.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileDto &&
          runtimeType == other.runtimeType &&
          npub == other.npub &&
          username == other.username;
}

class TaraMessageDto {
  final String id;
  final String text;
  final bool fromTara;
  final bool crisis;
  final BigInt createdAt;

  const TaraMessageDto({
    required this.id,
    required this.text,
    required this.fromTara,
    required this.crisis,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      text.hashCode ^
      fromTara.hashCode ^
      crisis.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaraMessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text &&
          fromTara == other.fromTara &&
          crisis == other.crisis &&
          createdAt == other.createdAt;
}

class TurnServerStatusDto {
  final bool configured;
  final String? url;

  const TurnServerStatusDto({
    required this.configured,
    this.url,
  });

  @override
  int get hashCode => configured.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TurnServerStatusDto &&
          runtimeType == other.runtimeType &&
          configured == other.configured &&
          url == other.url;
}

@freezed
sealed class UiError with _$UiError implements FrbException {
  const UiError._();

  const factory UiError.unknownWorkspace(
    String field0,
  ) = UiError_UnknownWorkspace;
  const factory UiError.transition(
    String field0,
  ) = UiError_Transition;
  const factory UiError.noIdentity() = UiError_NoIdentity;
  const factory UiError.storeLocked() = UiError_StoreLocked;
  const factory UiError.crypto(
    String field0,
  ) = UiError_Crypto;
  const factory UiError.storage(
    String field0,
  ) = UiError_Storage;
  const factory UiError.vaultLocked() = UiError_VaultLocked;
  const factory UiError.engine(
    String field0,
  ) = UiError_Engine;
}

class UpiIntentDto {
  final double amountInr;
  final String vpa;
  final String uri;

  const UpiIntentDto({
    required this.amountInr,
    required this.vpa,
    required this.uri,
  });

  @override
  int get hashCode => amountInr.hashCode ^ vpa.hashCode ^ uri.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpiIntentDto &&
          runtimeType == other.runtimeType &&
          amountInr == other.amountInr &&
          vpa == other.vpa &&
          uri == other.uri;
}

class WorkspaceDto {
  final String key;
  final String label;
  final bool active;
  final bool relayConnected;
  final bool meshActive;
  final bool coupleSandbox;

  const WorkspaceDto({
    required this.key,
    required this.label,
    required this.active,
    required this.relayConnected,
    required this.meshActive,
    required this.coupleSandbox,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      label.hashCode ^
      active.hashCode ^
      relayConnected.hashCode ^
      meshActive.hashCode ^
      coupleSandbox.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          active == other.active &&
          relayConnected == other.relayConnected &&
          meshActive == other.meshActive &&
          coupleSandbox == other.coupleSandbox;
}
