// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<BridgeEvent> dco_decode_StreamSink_bridge_event_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CallSignal dco_decode_box_autoadd_call_signal(dynamic raw);

  @protected
  CallSignalDto dco_decode_box_autoadd_call_signal_dto(dynamic raw);

  @protected
  ChitthiDto dco_decode_box_autoadd_chitthi_dto(dynamic raw);

  @protected
  DirectMessageDto dco_decode_box_autoadd_direct_message_dto(dynamic raw);

  @protected
  IdentityDto dco_decode_box_autoadd_identity_dto(dynamic raw);

  @protected
  MediaMessageDto dco_decode_box_autoadd_media_message_dto(dynamic raw);

  @protected
  MeshStatusDto dco_decode_box_autoadd_mesh_status_dto(dynamic raw);

  @protected
  MessageRequestDto dco_decode_box_autoadd_message_request_dto(dynamic raw);

  @protected
  PresenceDto dco_decode_box_autoadd_presence_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  BridgeEvent dco_decode_bridge_event(dynamic raw);

  @protected
  CallMediaKind dco_decode_call_media_kind(dynamic raw);

  @protected
  CallRecordDto dco_decode_call_record_dto(dynamic raw);

  @protected
  CallSessionDto dco_decode_call_session_dto(dynamic raw);

  @protected
  CallSignal dco_decode_call_signal(dynamic raw);

  @protected
  CallSignalDto dco_decode_call_signal_dto(dynamic raw);

  @protected
  ChitthiDto dco_decode_chitthi_dto(dynamic raw);

  @protected
  ComradeDto dco_decode_comrade_dto(dynamic raw);

  @protected
  ContactDto dco_decode_contact_dto(dynamic raw);

  @protected
  ConversationDto dco_decode_conversation_dto(dynamic raw);

  @protected
  CrisisResourceDto dco_decode_crisis_resource_dto(dynamic raw);

  @protected
  DirectMessageDto dco_decode_direct_message_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FoundProfileDto dco_decode_found_profile_dto(dynamic raw);

  @protected
  HangupReason dco_decode_hangup_reason(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  IceServerDto dco_decode_ice_server_dto(dynamic raw);

  @protected
  IceStrategy dco_decode_ice_strategy(dynamic raw);

  @protected
  IdentityDto dco_decode_identity_dto(dynamic raw);

  @protected
  JournalEntryDto dco_decode_journal_entry_dto(dynamic raw);

  @protected
  KeypairDto dco_decode_keypair_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CallRecordDto> dco_decode_list_call_record_dto(dynamic raw);

  @protected
  List<ChitthiDto> dco_decode_list_chitthi_dto(dynamic raw);

  @protected
  List<ComradeDto> dco_decode_list_comrade_dto(dynamic raw);

  @protected
  List<ContactDto> dco_decode_list_contact_dto(dynamic raw);

  @protected
  List<ConversationDto> dco_decode_list_conversation_dto(dynamic raw);

  @protected
  List<CrisisResourceDto> dco_decode_list_crisis_resource_dto(dynamic raw);

  @protected
  List<FoundProfileDto> dco_decode_list_found_profile_dto(dynamic raw);

  @protected
  List<IceServerDto> dco_decode_list_ice_server_dto(dynamic raw);

  @protected
  List<JournalEntryDto> dco_decode_list_journal_entry_dto(dynamic raw);

  @protected
  List<MediaMessageDto> dco_decode_list_media_message_dto(dynamic raw);

  @protected
  List<MessageDto> dco_decode_list_message_dto(dynamic raw);

  @protected
  List<MessageRequestDto> dco_decode_list_message_request_dto(dynamic raw);

  @protected
  List<MetricDto> dco_decode_list_metric_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TaraMessageDto> dco_decode_list_tara_message_dto(dynamic raw);

  @protected
  List<UpiIntentDto> dco_decode_list_upi_intent_dto(dynamic raw);

  @protected
  List<WorkspaceDto> dco_decode_list_workspace_dto(dynamic raw);

  @protected
  List<WorkspaceKeyLabel> dco_decode_list_workspace_key_label(dynamic raw);

  @protected
  MediaBytesDto dco_decode_media_bytes_dto(dynamic raw);

  @protected
  MediaMessageDto dco_decode_media_message_dto(dynamic raw);

  @protected
  MeshStatusDto dco_decode_mesh_status_dto(dynamic raw);

  @protected
  MessageDto dco_decode_message_dto(dynamic raw);

  @protected
  MessageRequestDto dco_decode_message_request_dto(dynamic raw);

  @protected
  MetricDto dco_decode_metric_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  IdentityDto? dco_decode_opt_box_autoadd_identity_dto(dynamic raw);

  @protected
  PresenceDto? dco_decode_opt_box_autoadd_presence_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  PresenceDto dco_decode_presence_dto(dynamic raw);

  @protected
  ProfileDto dco_decode_profile_dto(dynamic raw);

  @protected
  TaraMessageDto dco_decode_tara_message_dto(dynamic raw);

  @protected
  TurnServerStatusDto dco_decode_turn_server_status_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiError dco_decode_ui_error(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpiIntentDto dco_decode_upi_intent_dto(dynamic raw);

  @protected
  WorkspaceDto dco_decode_workspace_dto(dynamic raw);

  @protected
  WorkspaceKeyLabel dco_decode_workspace_key_label(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<BridgeEvent> sse_decode_StreamSink_bridge_event_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CallSignal sse_decode_box_autoadd_call_signal(SseDeserializer deserializer);

  @protected
  CallSignalDto sse_decode_box_autoadd_call_signal_dto(
      SseDeserializer deserializer);

  @protected
  ChitthiDto sse_decode_box_autoadd_chitthi_dto(SseDeserializer deserializer);

  @protected
  DirectMessageDto sse_decode_box_autoadd_direct_message_dto(
      SseDeserializer deserializer);

  @protected
  IdentityDto sse_decode_box_autoadd_identity_dto(SseDeserializer deserializer);

  @protected
  MediaMessageDto sse_decode_box_autoadd_media_message_dto(
      SseDeserializer deserializer);

  @protected
  MeshStatusDto sse_decode_box_autoadd_mesh_status_dto(
      SseDeserializer deserializer);

  @protected
  MessageRequestDto sse_decode_box_autoadd_message_request_dto(
      SseDeserializer deserializer);

  @protected
  PresenceDto sse_decode_box_autoadd_presence_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  BridgeEvent sse_decode_bridge_event(SseDeserializer deserializer);

  @protected
  CallMediaKind sse_decode_call_media_kind(SseDeserializer deserializer);

  @protected
  CallRecordDto sse_decode_call_record_dto(SseDeserializer deserializer);

  @protected
  CallSessionDto sse_decode_call_session_dto(SseDeserializer deserializer);

  @protected
  CallSignal sse_decode_call_signal(SseDeserializer deserializer);

  @protected
  CallSignalDto sse_decode_call_signal_dto(SseDeserializer deserializer);

  @protected
  ChitthiDto sse_decode_chitthi_dto(SseDeserializer deserializer);

  @protected
  ComradeDto sse_decode_comrade_dto(SseDeserializer deserializer);

  @protected
  ContactDto sse_decode_contact_dto(SseDeserializer deserializer);

  @protected
  ConversationDto sse_decode_conversation_dto(SseDeserializer deserializer);

  @protected
  CrisisResourceDto sse_decode_crisis_resource_dto(
      SseDeserializer deserializer);

  @protected
  DirectMessageDto sse_decode_direct_message_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FoundProfileDto sse_decode_found_profile_dto(SseDeserializer deserializer);

  @protected
  HangupReason sse_decode_hangup_reason(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  IceServerDto sse_decode_ice_server_dto(SseDeserializer deserializer);

  @protected
  IceStrategy sse_decode_ice_strategy(SseDeserializer deserializer);

  @protected
  IdentityDto sse_decode_identity_dto(SseDeserializer deserializer);

  @protected
  JournalEntryDto sse_decode_journal_entry_dto(SseDeserializer deserializer);

  @protected
  KeypairDto sse_decode_keypair_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CallRecordDto> sse_decode_list_call_record_dto(
      SseDeserializer deserializer);

  @protected
  List<ChitthiDto> sse_decode_list_chitthi_dto(SseDeserializer deserializer);

  @protected
  List<ComradeDto> sse_decode_list_comrade_dto(SseDeserializer deserializer);

  @protected
  List<ContactDto> sse_decode_list_contact_dto(SseDeserializer deserializer);

  @protected
  List<ConversationDto> sse_decode_list_conversation_dto(
      SseDeserializer deserializer);

  @protected
  List<CrisisResourceDto> sse_decode_list_crisis_resource_dto(
      SseDeserializer deserializer);

  @protected
  List<FoundProfileDto> sse_decode_list_found_profile_dto(
      SseDeserializer deserializer);

  @protected
  List<IceServerDto> sse_decode_list_ice_server_dto(
      SseDeserializer deserializer);

  @protected
  List<JournalEntryDto> sse_decode_list_journal_entry_dto(
      SseDeserializer deserializer);

  @protected
  List<MediaMessageDto> sse_decode_list_media_message_dto(
      SseDeserializer deserializer);

  @protected
  List<MessageDto> sse_decode_list_message_dto(SseDeserializer deserializer);

  @protected
  List<MessageRequestDto> sse_decode_list_message_request_dto(
      SseDeserializer deserializer);

  @protected
  List<MetricDto> sse_decode_list_metric_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TaraMessageDto> sse_decode_list_tara_message_dto(
      SseDeserializer deserializer);

  @protected
  List<UpiIntentDto> sse_decode_list_upi_intent_dto(
      SseDeserializer deserializer);

  @protected
  List<WorkspaceDto> sse_decode_list_workspace_dto(
      SseDeserializer deserializer);

  @protected
  List<WorkspaceKeyLabel> sse_decode_list_workspace_key_label(
      SseDeserializer deserializer);

  @protected
  MediaBytesDto sse_decode_media_bytes_dto(SseDeserializer deserializer);

  @protected
  MediaMessageDto sse_decode_media_message_dto(SseDeserializer deserializer);

  @protected
  MeshStatusDto sse_decode_mesh_status_dto(SseDeserializer deserializer);

  @protected
  MessageDto sse_decode_message_dto(SseDeserializer deserializer);

  @protected
  MessageRequestDto sse_decode_message_request_dto(
      SseDeserializer deserializer);

  @protected
  MetricDto sse_decode_metric_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  IdentityDto? sse_decode_opt_box_autoadd_identity_dto(
      SseDeserializer deserializer);

  @protected
  PresenceDto? sse_decode_opt_box_autoadd_presence_dto(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  PresenceDto sse_decode_presence_dto(SseDeserializer deserializer);

  @protected
  ProfileDto sse_decode_profile_dto(SseDeserializer deserializer);

  @protected
  TaraMessageDto sse_decode_tara_message_dto(SseDeserializer deserializer);

  @protected
  TurnServerStatusDto sse_decode_turn_server_status_dto(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiError sse_decode_ui_error(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpiIntentDto sse_decode_upi_intent_dto(SseDeserializer deserializer);

  @protected
  WorkspaceDto sse_decode_workspace_dto(SseDeserializer deserializer);

  @protected
  WorkspaceKeyLabel sse_decode_workspace_key_label(
      SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_bridge_event_Sse(
      RustStreamSink<BridgeEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_call_signal(
      CallSignal self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_call_signal_dto(
      CallSignalDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_chitthi_dto(
      ChitthiDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_direct_message_dto(
      DirectMessageDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_identity_dto(
      IdentityDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_media_message_dto(
      MediaMessageDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mesh_status_dto(
      MeshStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_message_request_dto(
      MessageRequestDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_presence_dto(
      PresenceDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_event(BridgeEvent self, SseSerializer serializer);

  @protected
  void sse_encode_call_media_kind(CallMediaKind self, SseSerializer serializer);

  @protected
  void sse_encode_call_record_dto(CallRecordDto self, SseSerializer serializer);

  @protected
  void sse_encode_call_session_dto(
      CallSessionDto self, SseSerializer serializer);

  @protected
  void sse_encode_call_signal(CallSignal self, SseSerializer serializer);

  @protected
  void sse_encode_call_signal_dto(CallSignalDto self, SseSerializer serializer);

  @protected
  void sse_encode_chitthi_dto(ChitthiDto self, SseSerializer serializer);

  @protected
  void sse_encode_comrade_dto(ComradeDto self, SseSerializer serializer);

  @protected
  void sse_encode_contact_dto(ContactDto self, SseSerializer serializer);

  @protected
  void sse_encode_conversation_dto(
      ConversationDto self, SseSerializer serializer);

  @protected
  void sse_encode_crisis_resource_dto(
      CrisisResourceDto self, SseSerializer serializer);

  @protected
  void sse_encode_direct_message_dto(
      DirectMessageDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_found_profile_dto(
      FoundProfileDto self, SseSerializer serializer);

  @protected
  void sse_encode_hangup_reason(HangupReason self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_ice_server_dto(IceServerDto self, SseSerializer serializer);

  @protected
  void sse_encode_ice_strategy(IceStrategy self, SseSerializer serializer);

  @protected
  void sse_encode_identity_dto(IdentityDto self, SseSerializer serializer);

  @protected
  void sse_encode_journal_entry_dto(
      JournalEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_keypair_dto(KeypairDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_call_record_dto(
      List<CallRecordDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chitthi_dto(
      List<ChitthiDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_comrade_dto(
      List<ComradeDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_contact_dto(
      List<ContactDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_conversation_dto(
      List<ConversationDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_crisis_resource_dto(
      List<CrisisResourceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_found_profile_dto(
      List<FoundProfileDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ice_server_dto(
      List<IceServerDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_journal_entry_dto(
      List<JournalEntryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_media_message_dto(
      List<MediaMessageDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_message_dto(
      List<MessageDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_message_request_dto(
      List<MessageRequestDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_metric_dto(
      List<MetricDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_tara_message_dto(
      List<TaraMessageDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_upi_intent_dto(
      List<UpiIntentDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_workspace_dto(
      List<WorkspaceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_workspace_key_label(
      List<WorkspaceKeyLabel> self, SseSerializer serializer);

  @protected
  void sse_encode_media_bytes_dto(MediaBytesDto self, SseSerializer serializer);

  @protected
  void sse_encode_media_message_dto(
      MediaMessageDto self, SseSerializer serializer);

  @protected
  void sse_encode_mesh_status_dto(MeshStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_message_dto(MessageDto self, SseSerializer serializer);

  @protected
  void sse_encode_message_request_dto(
      MessageRequestDto self, SseSerializer serializer);

  @protected
  void sse_encode_metric_dto(MetricDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_identity_dto(
      IdentityDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_presence_dto(
      PresenceDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_presence_dto(PresenceDto self, SseSerializer serializer);

  @protected
  void sse_encode_profile_dto(ProfileDto self, SseSerializer serializer);

  @protected
  void sse_encode_tara_message_dto(
      TaraMessageDto self, SseSerializer serializer);

  @protected
  void sse_encode_turn_server_status_dto(
      TurnServerStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_error(UiError self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_upi_intent_dto(UpiIntentDto self, SseSerializer serializer);

  @protected
  void sse_encode_workspace_dto(WorkspaceDto self, SseSerializer serializer);

  @protected
  void sse_encode_workspace_key_label(
      WorkspaceKeyLabel self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
