// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A freshly generated secp256k1 keypair, Bech32-encoded. Standalone —
/// doesn't touch the encrypted store; see [`Comrade::generate_identity`] and
/// [`Comrade::unlock_vault`] for the store-backed identity flow every UI
/// screen actually drives.
class KeypairDto {
  final String npub;
  final String nsec;

  const KeypairDto({
    required this.npub,
    required this.nsec,
  });

  @override
  int get hashCode => npub.hashCode ^ nsec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeypairDto &&
          runtimeType == other.runtimeType &&
          npub == other.npub &&
          nsec == other.nsec;
}

/// A workspace discriminant paired with its display label.
class WorkspaceKeyLabel {
  final String key;
  final String label;

  const WorkspaceKeyLabel({
    required this.key,
    required this.label,
  });

  @override
  int get hashCode => key.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceKeyLabel &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label;
}
